- packages/satyrographos/satyrographos.0.0.1.5/opam
A naive package manager for SATySFi
Satyrographos is a naive package manager for [SATySFi].
---
---
> Package satyrographos.0.0.1.5

- packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.03.10/opam
Hi! Thank you for the very useful repo!
I can't install `satysfi.0.0.3+dev2019.03.10` and `satysfi-lib-dist.0.0.3+dev2019.03.10` together because `satysfi-lib-dist.0.0.3+dev2019.03.10` depends on `satysfi.0.0.3+dev2019.02.13`.
I think it should be `0.0.3+dev2019.03.10`.
> Bump satysfi version of satysfi-lib-dist.0.0.3+dev2019.03.10

- packages/satyrographos/satyrographos.0.0.2.0/opam
> Package satyrographos.0.0.2.0

- .travis.yml
- packages/satyrographos/satyrographos.0.0.2.1/opam
> Package satyrographos.0.0.2.1

- .travis.yml
- packages/satysfi-grcnum-doc/satysfi-grcnum-doc.0.2/opam
- packages/satysfi-grcnum/satysfi-grcnum.0.2/opam
-`satysfi-grcnum.0.2`: SATySFi Package for Greek Numeral System
-`satysfi-grcnum-doc.0.2`: Documentation of SATySFi Package for Greek Numeral System
---
* Source repo: git+https://github.com/na4zagin3/SATySFi-grcnum.git
---
> 2 packages from na4zagin3/SATySFi-grcnum at 0.2

- packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.11.16/files/fix-install-libs.patch
- packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.11.16/opam
- packages/satysfi/satysfi.0.0.3+dev2019.11.16/opam
I've added current snapshot of SATySFi because I want a fix of otfm (https://github.com/gfngfn/otfm/pull/7).
<details>
<summary>diff from previous snapshot (0.0.3+dev2019.07.14)</summary>
```
❯ diff -u satysfi/satysfi.0.0.3+dev2019.07.14/opam satysfi/satysfi.0.0.3+dev2019.11.16/opam
--- satysfi/satysfi.0.0.3+dev2019.07.14/opam    2019-11-16 13:31:17.000000000 +0900
+++ satysfi/satysfi.0.0.3+dev2019.11.16/opam    2019-11-16 16:31:23.000000000 +0900
@@ -1,6 +1,6 @@
opam-version: "2.0"
name: "satysfi"
-version: "0.0.3+dev2019.07.14"
+version: "0.0.3+dev2019.11.16"
maintainer: "SAKAMOTO Noriaki <mrty.ityt.pt@gmail.com>"
authors: [
"gfngfn"
@@ -30,7 +30,7 @@
"dune" {build}
"menhir"
"ocamlfind" {build}
-  "otfm" {= "0.3.6+satysfi"}
+  "otfm" {= "0.3.7+satysfi"}
"ppx_deriving"
"re" {build} …
```
> Add satysfi.0.0.3+dev2019.11.16 and satysfi-lib-dist.0.0.3+dev2019.11.16

- .travis.yml
- packages/satysfi-class-stjarticle-doc/satysfi-class-stjarticle-doc.1.3.2/opam
- packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2/opam
-`satysfi-class-stjarticle.1.3.2`: Extended SATySFi document package for Japanese
-`satysfi-class-stjarticle-doc.1.3.2`: Document: Extended SATySFi document package for Japanese
---
* Homepage: https://github.com/puripuri2100/stjarticle
* Source repo: git+https://github.com/puripuri2100/stjarticle.git
* Bug tracker: https://github.com/puripuri2100/stjarticle/issues
---
> Packages satysfi-class-stjarticle.1.3.2 and satysfi-class-stjarticle-doc.1.3.2

- packages/satysfi/satysfi.0.0.3+dev2018.10.29/opam
- packages/satysfi/satysfi.0.0.3+dev2019.02.10/opam
- packages/satysfi/satysfi.0.0.3+dev2019.02.13/opam
- packages/satysfi/satysfi.0.0.3+dev2019.03.10/opam
- packages/satysfi/satysfi.0.0.3+dev2019.07.14/opam
- packages/satysfi/satysfi.0.0.3+dev2019.11.16/opam
- packages/satysfi/satysfi.0.0.3/opam
See https://github.com/gfngfn/SATySFi/pull/206 for details.
Related: https://github.com/amutake/satysfi-docker/pull/9
> Restrict core_kernel version for SATySFi

- packages/satysfi-base/satysfi-base.1.0.0/opam
> Package satysfi-base.1.0.0

- .travis.yml
- packages/satyrographos/satyrographos.0.0.2.2/opam
> Package satyrographos.0.0.2.2

- packages/satysfi-base/satysfi-base.1.1.1/opam
> Package satysfi-base.1.1.1

- .travis.yml
- packages/satysfi-fonts-dejavu-doc/satysfi-fonts-dejavu-doc.2.37/opam
- packages/satysfi-fonts-dejavu/satysfi-fonts-dejavu.2.37/opam
-`satysfi-fonts-dejavu.2.37`: SATySFi Font Package for DejaVu Fonts
-`satysfi-fonts-dejavu-doc.2.37`: Document of SATySFi Font Package for DejaVu Fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-dejavu
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-dejavu.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-dejavu/issues
---
> 2 packages from zeptometer/SATySFi-fonts-dejavu at 2.37

- packages/satysfi/satysfi.0.0.4/opam
I've noticed that url section in opam file of satysfi.0.0.4 is duplicated.
(This git hash points to satysfi.0.0.3+dev2019.11.16)
> Remove duplicate url in satysfi.0.0.4

- packages/satysfi-fonts-dejavu-doc/satysfi-fonts-dejavu-doc.2.37+satysfi0.0.4/opam
- packages/satysfi-fonts-dejavu/satysfi-fonts-dejavu.2.37+satysfi0.0.4/opam
-`satysfi-fonts-dejavu.2.37+satysfi0.0.4`: SATySFi Font Package for DejaVu Fonts
-`satysfi-fonts-dejavu-doc.2.37+satysfi0.0.4`: Document of SATySFi Font Package for DejaVu Fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-dejavu
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-dejavu.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-dejavu/issues
---
> 2 packages from zeptometer/SATySFi-fonts-dejavu at 2.37+satysfi0.0.4

- .travis.yml
- packages/satysfi-fonts-asana-math-doc/satysfi-fonts-asana-math-doc.2.37+satysfi0.0.4/opam
- packages/satysfi-fonts-asana-math/satysfi-fonts-asana-math.2.37+satysfi0.0.4/opam
-`satysfi-fonts-asana-math.2.37+satysfi0.0.4`: SATySFi Font Package for Asana Math Fonts
-`satysfi-fonts-asana-math-doc.2.37+satysfi0.0.4`: Document of SATySFi Font Package for Asana Math Fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-asana-math
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-asana-math.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-asana-math/issues
---
> 2 packages from zeptometer/SATySFi-fonts-asana at 2.37+satysfi0.0.4

- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.13/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.03.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.07.14/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.11.16/opam
- packages/satysfi-dist/satysfi-dist.0.0.4/opam
- packages/satysfi/satysfi.0.0.3+dev2018.10.29/opam
- packages/satysfi/satysfi.0.0.3/opam
I uploaded fonts used by satysfi-dist to https://github.com/na4zagin3/satysfi-dist-font-archives
This PR it to specify the mirror URL of IPAexfont00301.zip.
> Specify a mirror of IPAexfont00301.zip

- packages/satysfi-base/satysfi-base.1.2.0/opam
> Package satysfi-base.1.2.0

- .travis.yml
- packages/satysfi-fonts-computer-modern-unicode-doc/satysfi-fonts-computer-modern-unicode-doc.0.7.0+satysfi0.0.4/opam
- packages/satysfi-fonts-computer-modern-unicode/satysfi-fonts-computer-modern-unicode.0.7.0+satysfi0.0.4/opam
-`satysfi-fonts-computer-modern-unicode.0.7.0+satysfi0.0.4`: SATySFi Font Package for Computer Modern Unicode fonts
-`satysfi-fonts-computer-modern-unicode-doc.0.7.0+satysfi0.0.4`: Document of SATySFi Font Package for Computer Modern Unicode fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-computer-modern-unicode
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-computer-modern-unicode.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-computer-modern-unicode/issues
---
> 2 packages from zeptometer/SATySFi-fonts-computer-modern-unicode at 0.7.0+satysfi0.0.4

- .travis.yml
- packages/satysfi-fonts-noto-serif-cjk-jp-doc/satysfi-fonts-noto-serif-cjk-jp-doc.1.001+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.1.001+satysfi0.0.4/opam
-`satysfi-fonts-noto-serif-cjk-jp.1.001+satysfi0.0.4`: SATySFi Font Package for Noto Serif CJK JP fonts
-`satysfi-fonts-noto-serif-cjk-jp-doc.1.001+satysfi0.0.4`: Document of SATySFi Font Package for Noto Serif CJK JP fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-serif-cjk-jp at 1.001+satysfi0.0.4

- .travis.yml
- packages/satyrographos/satyrographos.0.0.2.3/opam
> Package satyrographos.0.0.2.3

- .travis.yml
- packages/satysfi-fonts-noto-sans-cjk-jp-doc/satysfi-fonts-noto-sans-cjk-jp-doc.1.004+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.1.004+satysfi0.0.4/opam
-`satysfi-fonts-noto-sans-cjk-jp.1.004+satysfi0.0.4`: SATySFi Font Package for Noto Sans CJK JP fonts
-`satysfi-fonts-noto-sans-cjk-jp-doc.1.004+satysfi0.0.4`: Document of SATySFi Font Package for Noto Sans CJK JP fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-sans-cjk-jp at 1.004+satysfi0.0.4

- .travis.yml
- packages/satysfi-fonts-noto-sans-doc/satysfi-fonts-noto-sans-doc.2.000+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.000+satysfi0.0.4/opam
-`satysfi-fonts-noto-sans.2.000+satysfi0.0.4`: SATySFi Font Package for Noto Sans fonts
-`satysfi-fonts-noto-sans-doc.2.000+satysfi0.0.4`: Document of SATySFi Font Package for Noto Sans fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-sans
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-sans.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-sans/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-sans at 2.000+satysfi0.0.4

- .travis.yml
- packages/satysfi-fonts-noto-serif-doc/satysfi-fonts-noto-serif-doc.2.000+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.000+satysfi0.0.4/opam
-`satysfi-fonts-noto-serif.2.000+satysfi0.0.4`: SATySFi Font Package for Noto Serif fonts
-`satysfi-fonts-noto-serif-doc.2.000+satysfi0.0.4`: Document of SATySFi Font Package for Noto Serif fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-serif
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-serif.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-serif/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-serif at 2.000+satysfi0.0.4

- .travis.yml
- packages/satysfi-cancel/satysfi-cancel.0.0.0/opam
The cancel package
The SATySFi equivalent of the LateX's cancel package.
---
* Homepage: https://github.com/yuhr/satysfi-cancel
* Source repo: git+https://github.com/yuhr/satysfi-cancel.git
* Bug tracker: https://github.com/yuhr/satysfi-cancel/issues
---
> Package satysfi-cancel.0.0.0

- .travis.yml
- packages/satysfi-karnaugh-doc/satysfi-karnaugh-doc.0.0.1/opam
- packages/satysfi-karnaugh/satysfi-karnaugh.0.0.1/opam
Drawing Karnaugh maps in SATySFi
Drawing Karnaugh maps in SATySFi
This can be installed as a package for SATySFi by Satyrographos. (https://github.com/na4zagin3/satyrographos)
---
* Homepage: https://github.com/takagiy/satysfi-karnaugh
* Source repo: git+https://github.com/takagiy/satysfi-karnaugh.git
* Bug tracker: https://github.com/takagiy/satysfi-karnaugh/issues
---
---
Closes #18
> Package satysfi-karnaugh.0.0.1

- packages/satysfi-make-html/satysfi-make-html.0.1.0/opam
- packages/satysfi-make-markdown/satysfi-make-markdown.0.1.0/opam
This PR fixes synopsis fields which should start with a capital letter and not to have a period at the end.
> Fix synopsis fields

- packages/satysfi-zrbase/satysfi-zrbase.0.4.0/opam
SATySFi Packages for Ordinary Programming
ZR's SATySFi Package Collection for Ordinary Programming.
This requires Satyrographos to install. See https://github.com/na4zagin3/satyrographos.
Closes  #88
---
* Homepage: https://github.com/zr-tex8r/satysfi-zrbase
* Source repo: git+https://github.com/zr-tex8r/satysfi-zrbase.git
* Bug tracker: https://github.com/zr-tex8r/satysfi-zrbase
---
> Package satysfi-zrbase.0.4.0

- packages/satysfi-fonts-noto-emoji-doc/satysfi-fonts-noto-emoji-doc.1.05+uh+2/opam
- packages/satysfi-fonts-noto-emoji/satysfi-fonts-noto-emoji.1.05+uh+2/opam
-`satysfi-fonts-noto-emoji.1.05+uh+2`: SATySFi Font Package for Noto Emoji fonts
-`satysfi-fonts-noto-emoji-doc.1.05+uh+2`: Document of SATySFi Font Package for Noto Emoji fonts
---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-noto-emoji
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-noto-emoji.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-noto-emoji/issues
---
> 2 packages from puripuri2100/SATySFi-fonts-noto-color-emoji at 1.05+uh+2

- .travis.yml
- packages/satyrographos/satyrographos.0.0.2.4/opam
> Package satyrographos.0.0.2.4

- packages/satysfi-base/satysfi-base.1.2.1/opam
> Package satysfi-base.1.2.1

- .travis.yml
Downloading files for satysfi-fonts-asana-math fails (https://travis-ci.com/github/na4zagin3/satyrographos-repo/jobs/314410628).
This PR temporarily removes the package from CI. It would be restored with #96.
> Temporarily remove satysfi-fonts-asana-math from CI

- .travis.yml
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.05/files/fix-install-libs.patch
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.05/opam
- packages/satysfi/satysfi.0.0.4+dev2020.04.05/opam
This PR adds satysfi.0.0.4+dev2020.02.22, which requires OCaml 4.08 or later.
> Add satysfi.0.0.4+dev2020.02.22

- packages/satysfi-fonts-noto-sans-doc/satysfi-fonts-noto-sans-doc.2.001+1+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.001+1+satysfi0.0.4/opam
-`satysfi-fonts-noto-sans.2.001+1+satysfi0.0.4`: SATySFi Font Package for Noto Sans fonts
-`satysfi-fonts-noto-sans-doc.2.001+1+satysfi0.0.4`: Document of SATySFi Font Package for Noto Sans fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-sans
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-sans.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-sans/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-sans at 2.001+1+satysfi0.0.4

- packages/satysfi-fonts-noto-serif-doc/satysfi-fonts-noto-serif-doc.2.001+1+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.001+1+satysfi0.0.4/opam
-`satysfi-fonts-noto-serif.2.001+1+satysfi0.0.4`: SATySFi Font Package for Noto Serif fonts
-`satysfi-fonts-noto-serif-doc.2.001+1+satysfi0.0.4`: Document of SATySFi Font Package for Noto Serif fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-serif
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-serif.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-serif/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-serif at 2.001+1+satysfi0.0.4

- packages/satysfi-fonts-noto-sans-cjk-jp-doc/satysfi-fonts-noto-sans-cjk-jp-doc.2.001+1+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.2.001+1+satysfi0.0.4/opam
-`satysfi-fonts-noto-sans-cjk-jp.2.001+1+satysfi0.0.4`: SATySFi Font Package for Noto Sans CJK JP fonts
-`satysfi-fonts-noto-sans-cjk-jp-doc.2.001+1+satysfi0.0.4`: Document of SATySFi Font Package for Noto Sans CJK JP fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-sans-cjk-jp/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-sans-cjk-jp at 2.001+1+satysfi0.0.4

- packages/satysfi-fonts-noto-serif-cjk-jp-doc/satysfi-fonts-noto-serif-cjk-jp-doc.2.001+1+satysfi0.0.4/opam
- packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.2.001+1+satysfi0.0.4/opam
-`satysfi-fonts-noto-serif-cjk-jp.2.001+1+satysfi0.0.4`: SATySFi Font Package for Noto Serif CJK JP fonts
-`satysfi-fonts-noto-serif-cjk-jp-doc.2.001+1+satysfi0.0.4`: Document of SATySFi Font Package for Noto Serif CJK JP fonts
---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-noto-serif-cjk-jp/issues
---
> 2 packages from zeptometer/SATySFi-fonts-noto-serif-cjk-jp at 2.001+1+satysfi0.0.4

- packages/satysfi-uline/satysfi-uline.0.2.0/opam
- satyrographos-repo-test-develop.opam
- satyrographos-repo-test-stable.opam
Underline for SAtySFi
Underline for SAtySFi
---
* Homepage: https://github.com/puripuri2100/SATySFi-uline
* Source repo: git+https://github.com/puripuri2100/SATySFi-uline.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-uline/issues
---
> Package satysfi-uline.0.2.0

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.1/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.1/opam
- satyrographos-repo-test-develop.opam
- satyrographos-repo-test-stable.opam
-`satysfi-class-yabaitech.0.0.1`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.1`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.1

- packages/satyrographos/satyrographos.0.0.2.5/opam
> Package satyrographos.0.0.2.5

- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.0.0/opam
- packages/satysfi-easytable/satysfi-easytable.1.0.0/opam
- satyrographos-repo-test-develop.opam
- satyrographos-repo-test-stable-0-0-5.opam
A SATySFi package to build simple tables
-`satysfi-easytable.1.0.0`
-`satysfi-easytable-doc.1.0.0`
---
* Homepage: https://github.com/monaqa/satysfi-easytable
* Source repo: git+https://github.com/monaqa/satysfi-easytable.git
* Bug tracker: https://github.com/monaqa/satysfi-easytable/issues
---
> 2 packages from monaqa/satysfi-easytable at 1.0.0

- packages/satysfi-base/satysfi-base.1.3.0/opam
> Package satysfi-base.1.3.0

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.0.1/opam
- packages/satysfi-ncsq/satysfi-ncsq.0.0.1/opam
-`satysfi-ncsq.0.0.1`
-`satysfi-ncsq-doc.0.0.1`
---
---
> 2 packages from uemurax/satysfi-ncsq at 0.0.1

- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
Snapshot packages are unnecessarily licensed with LGPL3. This PR changes the license to CC0.
> Change LICENCE of snapshot packages

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.1.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.0.1.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-ncsq.0.1.0`
-`satysfi-ncsq-doc.0.1.0`
---
---
> 2 packages from uemurax/satysfi-ncsq at 0.1.0

- scripts/update-snapshot
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
This also fixes update-snapshot script
- Calculate diff from the common ancester of origin/master and HEAD instead of diff from master.
- Exclude satyrographos and packages prefixed with satyrographos-
> Fix dependencies of snapshots

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.2.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.0.2.0/opam
-`satysfi-ncsq.0.2.0`
-`satysfi-ncsq-doc.0.2.0`
---
---
> 2 packages from uemurax/satysfi-ncsq at 0.2.0

- packages/conf-yarn/conf-yarn.0.1/opam
This PR adds conf-yarn, which will be used for testing satysfi-base.
> Add conf-yarn.0.1

- travis.sh
Workaround a problem where error messages in Travis is like
```
+ opam install --json=opam-output.json --dry-run --strict --with-test satysfi.0.0.4 snapshot-stable-0-0-4 satysfi-ncsq-doc.1.0.0
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[snapshot-stable-0-0-4.~dev] synchronised from file:///home/travis/build/na4zagin3/satyrographos-repo
[NOTE] Package satysfi is already installed (current version is 0.0.4).
The following dependencies couldn't be met:
- satysfi-ncsq-doc → satysfi-easytable → satysfi >= 0.0.5 → ocaml >= 4.08.0
base of this switch (use `--unlock-base' to force)
No solution found, exiting
```
```
+ opam install --json=opam-output.json --dry-run --strict --with-test satysfi.0.0.4 snapshot-stable-0-0-4 satysfi-ncsq.1.0.0
<><> Synchronising …
```
> Workaround OPAM fails in different error messages in Travis

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.1.0.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.1.0.0/opam
-`satysfi-ncsq.1.0.0`
-`satysfi-ncsq-doc.1.0.0`
---
---
> 2 packages from uemurax/satysfi-ncsq at 1.0.0

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.2/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.2/opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.2`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.2`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.2

- packages/satysfi-lipsum/satysfi-lipsum.0.2.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
A SATySFi package of dummy text
A SATySFi package of dummy text.
---
* Homepage: https://github.com/puripuri2100/SATySFi-lipsum
* Source repo: git+https://github.com/puripuri2100/SATySFi-lipsum.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-lipsum/issues
---
> Package satysfi-lipsum.0.2.0

- packages/satyrographos/satyrographos.0.0.2.5/files/allow-unannotated-ignores.patch
- packages/satyrographos/satyrographos.0.0.2.5/opam
[ppx_js_style](https://github.com/janestreet/ppx_js_style) started to
report false positive warnings.  This PR keep it from reporting
them.
> Apply patch to squelch false positive warnings

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.2.0.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.2.0.0/opam
- snapshot-stable-0-0-5.opam
-`satysfi-ncsq.2.0.0`
-`satysfi-ncsq-doc.2.0.0`
---
---
> 2 packages from uemurax/satysfi-ncsq at 2.0.0

- packages/satyrographos/satyrographos.0.0.2.6/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
> Package satyrographos.0.0.2.6

- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/files/fix-install-libs.patch
- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/opam
- packages/satysfi/satysfi.0.0.5+dev2020.09.05/opam
- snapshot-develop.opam
This PR adds a new development version of SATySFI with version satysfi.0.0.5+dev2020.09.05.
Differences: https://github.com/gfngfn/SATySFi/compare/v0.0.5...4e8ea2147f66b8c26a494067b3011e480be6526e#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
> Add satysfi dev version satysfi.0.0.5+dev2020.09.05

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.3/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.3/opam
- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.3`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.3`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.3

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.4/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.4/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.4`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.4`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.4

- packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
- packages/satysfi-arrows/satysfi-arrows.0.1.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
A SATySFi arrows library
-`satysfi-arrows.0.1.0`
-`satysfi-arrows-doc.0.1.0`
---
* Homepage: https://github.com/uemurax/satysfi-arrows
* Source repo: git+https://github.com/uemurax/satysfi-arrows.git
* Bug tracker: https://github.com/uemurax/satysfi-arrows/issues
---
> 2 packages from uemurax/satysfi-arrows at 0.1.0

- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.2.0/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.2.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
A SATySFi document class for creating presentations slides
-`satysfi-class-slydifi.0.2.0`
-`satysfi-class-slydifi-doc.0.2.0`
---
---
> 2 packages from monaqa/slydifi at 0.2.0

- packages/satysfi-fonts-junicode-doc/satysfi-fonts-junicode-doc.1.0002+satysfi0.0.5/opam
- packages/satysfi-fonts-junicode/satysfi-fonts-junicode.1.0002+satysfi0.0.5/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-fonts-junicode.1.0002+satysfi0.0.5`: SATySFi Font Package for Junicode
-`satysfi-fonts-junicode-doc.1.0002+satysfi0.0.5`: Document of SATySFi Font Package for Junicode
---
* Homepage: https://github.com/na4zagin3/SATySFi-fonts-junicode
* Source repo: git+https://github.com/na4zagin3/SATySFi-fonts-junicode.git
* Bug tracker: https://github.com/na4zagin3/SATySFi-fonts-junicode/issues
---
> 2 packages from na4zagin3/SATySFi-fonts-junicode at 1.0002+satysfi0.0.5

- packages/satysfi-fss-doc/satysfi-fss-doc.0.0.1/opam
- packages/satysfi-fss/satysfi-fss.0.0.1/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-fss.0.0.1`: Font selection scheme
-`satysfi-fss-doc.0.0.1`: Document: Font selection scheme
---
* Homepage: https://github.com/na4zagin3/satysfi-fss
* Source repo: git+https://github.com/na4zagin3/satysfi-fss.git
* Bug tracker: https://github.com/na4zagin3/satysfi-fss/issues
---
> 2 packages from na4zagin3/satysfi-fss at 0.0.1

- snapshot-develop.opam
satysfi-ncsq.2.0.0 was added only to the stable-0.0.5 snapshot but not the development snapshot, while it should be.
> Include satysfi-ncsq.2.0.0 in development snapshot

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.2.1.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.2.1.0/opam
- snapshot-develop.opam
-`satysfi-ncsq.2.1.0`
-`satysfi-ncsq-doc.2.1.0`
---
---
> 2 packages from uemurax/satysfi-ncsq at 2.1.0

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.5/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.5/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.5`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.5`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.5

- packages/satysfi-fonts-cormorant-doc/satysfi-fonts-cormorant-doc.3.601+satysfi0.0.5/opam
- packages/satysfi-fonts-cormorant/satysfi-fonts-cormorant.3.601+satysfi0.0.5/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-fonts-cormorant.3.601+satysfi0.0.5`: SATySFi Font Package for Cormorant
-`satysfi-fonts-cormorant-doc.3.601+satysfi0.0.5`: Document: SATySFi Font Package for Cormorant
---
* Homepage: https://github.com/na4zagin3/SATySFi-fonts-cormorant
* Source repo: git+https://github.com/na4zagin3/SATySFi-fonts-cormorant.git
* Bug tracker: https://github.com/na4zagin3/SATySFi-fonts-cormorant/issues
---
> 2 packages from na4zagin3/SATySFi-fonts-cormorant at 3.601+satysfi0.0.5

- scripts/update-snapshot
- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
This PR inserts a line break after every package version constraint in the snapshots to reduce possibility of merge conflicts.
> Add a line break after each package in snapshots 

- packages/satysfi-fonts-bodoni-star-doc/satysfi-fonts-bodoni-star-doc.2.3+satysfi0.0.5/opam
- packages/satysfi-fonts-bodoni-star/satysfi-fonts-bodoni-star.2.3+satysfi0.0.5/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-fonts-bodoni-star.2.3+satysfi0.0.5`: SATySFi Font Package for Bodoni*
-`satysfi-fonts-bodoni-star-doc.2.3+satysfi0.0.5`: Document: SATySFi Font Package for Bodoni*
---
* Homepage: https://github.com/na4zagin3/SATySFi-fonts-bodoni-star
* Source repo: git+https://github.com/na4zagin3/SATySFi-fonts-bodoni-star.git
* Bug tracker: https://github.com/na4zagin3/SATySFi-fonts-bodoni-star/issues
---
> 2 packages from na4zagin3/SATySFi-fonts-bodoni-star at 2.3+satysfi0.0.5

- travis.sh
----
This PR has the CI run `satyrographos install` every after package installation to check file collisions.
Closes #197.
> Check file duplication

- travis.sh
This PR runs `opam lint --strict` in the CI to catch errors.
> Run opam lint for in the CI

- packages/satysfi-ruby-doc/satysfi-ruby-doc.0.1.2/opam
- packages/satysfi-ruby/satysfi-ruby.0.1.2/opam
- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
Japanese-style ruby in SATySFi
-`satysfi-ruby.0.1.2`
-`satysfi-ruby-doc.0.1.2`
---
* Homepage: https://github.com/puripuri2100/SATySFi-ruby
* Source repo: git+https://github.com/puripuri2100/SATySFi-ruby.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-ruby/issues
---
> 2 packages from puripuri2100/SATySFi-ruby at 0.1.2

- packages/satysfi-fonts-noto-sans-cjk-sc-doc/satysfi-fonts-noto-sans-cjk-sc-doc.2.001+1/opam
- packages/satysfi-fonts-noto-sans-cjk-sc/satysfi-fonts-noto-sans-cjk-sc.2.001+1/opam
- snapshot-develop.opam
- snapshot-stable-0-0-4.opam
- snapshot-stable-0-0-5.opam
-`satysfi-fonts-noto-sans-cjk-sc.2.001+1`: SATySFi Font Package for Noto Sans CJK SC fonts
-`satysfi-fonts-noto-sans-cjk-sc-doc.2.001+1`: Document of SATySFi Font Package for Noto Sans CJK SC fonts
---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-noto-sans-cjk-sc
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-noto-sans-cjk-sc.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-noto-sans-cjk-sc/issues
---
> 2 packages from puripuri2100/SATySFi-fonts-noto-sans-cjk-sc at 2.001+1

- packages/satysfi-matrixcd/satysfi-matrixcd.0.0.1/opam
A package for SATySFi to draw commutative diagrams
---
* Homepage: https://github.com/abenori/satysfi-matrixcd/
* Source repo: git+https://github.com/abenori/satysfi-matrixcd.git
* Bug tracker: https://github.com/abenori/satysfi-matrixcd/issues
---
> Package satysfi-matrixcd.0.0.1

- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.1/opam
- packages/satysfi-azmath/satysfi-azmath.0.0.1/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
A SATySFi package containing A-to-Z mathematical commands
-`satysfi-azmath.0.0.1`
-`satysfi-azmath-doc.0.0.1`
---
* Homepage: https://github.com/monaqa/satysfi-azmath
* Source repo: git+https://github.com/monaqa/satysfi-azmath.git
* Bug tracker: https://github.com/monaqa/satysfi-azmath/issues
---
> 2 packages from monaqa/satysfi-azmath at 0.0.1

- scripts/add-satysfi
This PR have `script/add-satysfi` get a version string from `git describe`.
With `-d` option it uses the previous version schema.
> Support version schema of git-describe

- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.13/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.03.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.07.14/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.11.16/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.09/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.16/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.22/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.05/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.25/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.06.07/opam
- packages/satysfi-dist/satysfi-dist.0.0.4/opam
- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/opam
- packages/satysfi-dist/satysfi-dist.0.0.5/opam
- packages/satysfi/satysfi.0.0.3/opam
- resources/satysfi-dist.template
Distribution URLs of IPAFonts have been moved from `https://ipafont.ipa.go.jp/IPAexfont/*.zip` for `https://moji.or.jp/wp-content/ipafont/IPAexfont/*.zip`
See also:
- https://github.com/amutake/satysfi-docker/pull/26
- https://github.com/gfngfn/SATySFi/pull/240
Closes https://github.com/na4zagin3/satyrographos-repo/issues/206
> Fix distribution urls of IPAFont

- scripts/update-snapshot
This PR lets `update-snapshot` ignore changes on `satysfi-dist` packages
> Do not update satysfi-dist packages in the snapshots

- packages/satysfi-tombo-doc/satysfi-tombo-doc.0.1.0/opam
- packages/satysfi-tombo/satysfi-tombo.0.1.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-tombo.0.1.0`: Generate Japanese-style crop marks
-`satysfi-tombo-doc.0.1.0`: Document of Tombo Package
---
* Homepage: https://github.com/puripuri2100/satysfi-tombo
* Source repo: git+https://github.com/puripuri2100/satysfi-tombo.git
* Bug tracker: https://github.com/puripuri2100/satysfi-tombo/issues
---
> 2 packages from puripuri2100/satysfi-tombo at 0.1.0

- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.3/opam
- packages/satysfi-azmath/satysfi-azmath.0.0.3/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
A SATySFi package containing A-to-Z mathematical commands
-`satysfi-azmath.0.0.3`
-`satysfi-azmath-doc.0.0.3`
---
* Homepage: https://github.com/monaqa/satysfi-azmath
* Source repo: git+https://github.com/monaqa/satysfi-azmath.git
* Bug tracker: https://github.com/monaqa/satysfi-azmath/issues
---
> 2 packages from monaqa/satysfi-azmath at 0.0.3

- packages/satysfi-tombo-doc/satysfi-tombo-doc.0.2.0/opam
- packages/satysfi-tombo/satysfi-tombo.0.2.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-tombo.0.2.0`: Generate Japanese-style crop marks
-`satysfi-tombo-doc.0.2.0`: Document of Tombo Package
---
* Homepage: https://github.com/puripuri2100/satysfi-tombo
* Source repo: git+https://github.com/puripuri2100/satysfi-tombo.git
* Bug tracker: https://github.com/puripuri2100/satysfi-tombo/issues
---
> 2 packages from puripuri2100/satysfi-tombo at 0.2.0

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.6/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.6/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.6`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.6`: Document: The yabaitech.tokyo SATySFi class
file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.6

- packages/satysfi-make-latex-doc/satysfi-make-latex-doc.0.2.0/opam
- packages/satysfi-make-latex/satysfi-make-latex.0.2.0/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-make-latex.0.2.0`: Outputting LaTeX file using SATySFi's text-mode
-`satysfi-make-latex-doc.0.2.0`: Document of make-latex Package
---
* Homepage: https://github.com/puripuri2100/SATySFi-make-latex
* Source repo: git+https://github.com/puripuri2100/SATySFi-make-latex.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-make-latex/issues
---
> 2 packages from puripuri2100/SATySFi-textmode-latex-packages at 0.2.0

- packages/satysfi-texlogo-doc/satysfi-texlogo-doc.0.1.1/opam
- packages/satysfi-texlogo/satysfi-texlogo.0.1.1/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-texlogo.0.1.1`: TeX-family logos with SATySFi
-`satysfi-texlogo-doc.0.1.1`: Document of satysfi-texlogo
---
* Homepage: https://github.com/puripuri2100/SATySFi-texlogo
* Source repo: git+https://github.com/puripuri2100/SATySFi-texlogo.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-texlogo/issues
---
> 2 packages from puripuri2100/SATySFi-texlogo at 0.1.1

- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/files/fix-download-font-sh-shasum.patch
- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/opam
- packages/satysfi-dist/satysfi-dist.0.0.5/files/fix-download-font-sh-shasum.patch
- packages/satysfi-dist/satysfi-dist.0.0.5/opam
This commit backports https://github.com/gfngfn/SATySFi/pull/253
Closes https://github.com/na4zagin3/satyrographos-repo/issues/231
Fixes https://github.com/monaqa/slydifi/issues/15
> Backport patch to download-fonts.sh

- packages/satysfi-matrixcd/satysfi-matrixcd.0.0.2/opam
A package for SATySFi to draw commutative diagrams
---
* Homepage: https://github.com/abenori/satysfi-matrixcd/
* Source repo: git+https://github.com/abenori/satysfi-matrixcd.git
* Bug tracker: https://github.com/abenori/satysfi-matrixcd/issues
---
> Package satysfi-matrixcd.0.0.2

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.7/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.7/opam
- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
-`satysfi-class-yabaitech.0.0.7`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.7`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.7

- packages/satysfi-base/satysfi-base.1.4.0/opam
> Package satysfi-base.1.4.0

- packages/satysfi-matrixcd/satysfi-matrixcd.0.0.2/opam
This PR allows satysfi-matrixcd to use satysfi-base 1.4.0 too
- Add to snapshot ``
> Relax version constraint of satysfi-matrixcd

- packages/satysfi-derive/satysfi-derive.1.0.0/opam
SATySFi commands and DSL for displaying derivation trees with maintainable code
SATySFi commands and DSL for displaying derivation trees with maintainable code
This requires Satyrographos to install. See https://github.com/na4zagin3/satyrographos.
---
* Homepage: https://github.com/yabaitechtokyo/satysfi-derive
* Source repo: git+https://github.com/yabaitechtokyo/satysfi-derive.git
* Bug tracker: https://github.com/yabaitechtokyo/satysfi-derive/issues
---
Choose follow-up actions. Do not write anything after this section.
> Package satysfi-derive.1.0.0

- packages/satysfi-quotation-doc/satysfi-quotation-doc.0.1.0/opam
- packages/satysfi-quotation/satysfi-quotation.0.1.0/opam
-`satysfi-quotation.0.1.0`: A SATySFi package of quoting
-`satysfi-quotation-doc.0.1.0`: Document of satysfi-quotation
---
* Homepage: https://github.com/puripuri2100/SATySFi-quotation
* Source repo: git+https://github.com/puripuri2100/SATySFi-quotation.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-quotation/issues
---
> 2 packages from puripuri2100/SATySFi-quotation at 0.1.0

- packages/satysfi-quotation-doc/satysfi-quotation-doc.0.2.0/opam
- packages/satysfi-quotation/satysfi-quotation.0.2.0/opam
-`satysfi-quotation.0.2.0`: A SATySFi package of quoting
-`satysfi-quotation-doc.0.2.0`: Document of satysfi-quotation
---
* Homepage: https://github.com/puripuri2100/SATySFi-quotation
* Source repo: git+https://github.com/puripuri2100/SATySFi-quotation.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-quotation/issues
---
> 2 packages from puripuri2100/SATySFi-quotation at 0.2.0

- packages/satysfi-fonts-charis-sil-doc/satysfi-fonts-charis-sil-doc.1.0.0/opam
- packages/satysfi-fonts-charis-sil/satysfi-fonts-charis-sil.1.0.0/opam
-`satysfi-fonts-charis-sil.1.0.0`: SATySFi Font Package for Charis SIL
-`satysfi-fonts-charis-sil-doc.1.0.0`: Document of SATySFi Font Package for Charis SIL
---
* Homepage: https://github.com/yuhr/satysfi-fonts-charis-sil
* Source repo: git+https://github.com/yuhr/satysfi-fonts-charis-sil.git
* Bug tracker: https://github.com/yuhr/satysfi-fonts-charis-sil/issues
---
👇I don't understand what I am supposed to do for this. What do you mean by "choose"?
> Packages satysfi-fonts-charis-sil.1.0.0 and satysfi-fonts-charis-sil-doc.1.0.0

- snapshot-develop.opam
- snapshot-stable-0-0-5.opam
This PR follows up #255.
Adds satysfi-fonts-charis-sil-doc.1.0.0 satysfi-fonts-charis-sil.1.0.0 to develop and stable-0.0.5 snapshots
> Follow up #255

- packages/satysfi-fonts-inconsolata-doc/satysfi-fonts-inconsolata-doc.3.001/opam
- packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam
-`satysfi-fonts-inconsolata.3.001`: SATySFi Font Package for inconsolata fonts
-`satysfi-fonts-inconsolata-doc.3.001`: Document of SATySFi Font Package for inconsolata fonts
---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-inconsolata
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-inconsolata.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-inconsolata/issues
---
> 2 packages from puripuri2100/SATySFi-fonts-inconsolata at 3.001

- packages/satysfi-lipsum-doc/satysfi-lipsum-doc.0.2.1/opam
- packages/satysfi-lipsum/satysfi-lipsum.0.2.1/opam
-`satysfi-lipsum.0.2.1`: A SATySFi package of dummy text
-`satysfi-lipsum-doc.0.2.1`: Document: A SATySFi package of dummy text
---
* Homepage: https://github.com/puripuri2100/SATySFi-lipsum
* Source repo: git+https://github.com/puripuri2100/SATySFi-lipsum.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-lipsum/issues
---
> 2 packages from puripuri2100/SATySFi-lipsum at 0.2.1

- packages/satysfi-simple-itemize-doc/satysfi-simple-itemize-doc.1.0.2/opam
- packages/satysfi-simple-itemize/satysfi-simple-itemize.1.0.2/opam
Document: Simple bullet on SATySFi
-`satysfi-simple-itemize.1.0.2`
-`satysfi-simple-itemize-doc.1.0.2`
---
* Homepage: https://github.com/puripuri2100/SATySFi-simple-itemize
* Source repo: git+https://github.com/puripuri2100/SATySFi-simple-itemize.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-simple-itemize/issues
---
> 2 packages from puripuri2100/SATySFi-simple-itemize at 1.0.2

- packages/satysfi-uline-doc/satysfi-uline-doc.0.2.2/opam
- packages/satysfi-uline/satysfi-uline.0.2.2/opam
-`satysfi-uline.0.2.2`: Underline for SAtySFi
-`satysfi-uline-doc.0.2.2`: Document: Underline for SAtySFi
---
* Homepage: https://github.com/puripuri2100/SATySFi-uline
* Source repo: git+https://github.com/puripuri2100/SATySFi-uline.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-uline/issues
---
> 2 packages from puripuri2100/SATySFi-uline at 0.2.2

- packages/satysfi-musikui-doc/satysfi-musikui-doc.0.1.1/opam
- packages/satysfi-musikui/satysfi-musikui.0.1.1/opam
-`satysfi-musikui.0.1.1`: Easy expression of arithmetical restorations with SATySFi
-`satysfi-musikui-doc.0.1.1`: Document: Easy expression of arithmetical restorations with SATySFi
---
* Homepage: https://github.com/puripuri2100/musikui.satyh
* Source repo: git+https://github.com/puripuri2100/musikui.satyh.git
* Bug tracker: https://github.com/puripuri2100/musikui.satyh/issues
---
> 2 packages from puripuri2100/musikui.satyh at 0.1.1

- packages/satysfi-num-conversion-doc/satysfi-num-conversion-doc.0.1.4/opam
- packages/satysfi-num-conversion/satysfi-num-conversion.0.1.4/opam
-`satysfi-num-conversion.0.1.4`: Convert numbers to the following notation
-`satysfi-num-conversion-doc.0.1.4`: Document: Convert numbers to the following notation
---
* Homepage: https://github.com/puripuri2100/SATySFi-num-conversion
* Source repo: git+https://github.com/puripuri2100/SATySFi-num-conversion.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-num-conversion/issues
---
> 2 packages from puripuri2100/SATySFi-num-conversion at 0.1.4

- packages/satysfi-assert-eq-doc/satysfi-assert-eq-doc.0.1.2/opam
- packages/satysfi-assert-eq/satysfi-assert-eq.0.1.2/opam
-`satysfi-assert-eq.0.1.2`: Provides function as the Rust's assert_eq! macro
-`satysfi-assert-eq-doc.0.1.2`: Document: Provides function as the Rust's assert_eq! macro
---
* Homepage: https://github.com/puripuri2100/SATySFi-assert-eq
* Source repo: git+https://github.com/puripuri2100/SATySFi-assert-eq.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-assert-eq/issues
---
> 2 packages from puripuri2100/SATySFi-assert-eq at 0.1.2

- packages/satysfi-debug-show-value-doc/satysfi-debug-show-value-doc.0.1.2/opam
- packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.2/opam
-`satysfi-debug-show-value.0.1.2`: Stringify SATySFi's value
-`satysfi-debug-show-value-doc.0.1.2`: Document: Stringify SATySFi's value
---
* Homepage: https://github.com/puripuri2100/SATySFi-debug-show-value
* Source repo: git+https://github.com/puripuri2100/SATySFi-debug-show-value.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-debug-show-value/issues
---
> 2 packages from puripuri2100/SATySFi-debug-show-value at 0.1.2

- packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.2/opam
> Fix dependency of  satysfi-debug-show-value

- packages/satysfi-test/satysfi-test.0.0.1/opam
For some reason, opam-publish fails to fails to create PR. Hence I manually create this PR :(
---
Unit testing framework for SATySFi
- satysfi-test:0.0.1
---
- Homepage: https://github.com/zeptometer/satysfi-test
- Source repo: git+https://github.com/zeptometer/satysfi-test
- Bug tracker: https://github.com/zeptometer/satysfi-test
---
> Package satysfi-test.0.0.1

- packages/satysfi-siunitx-doc/satysfi-siunitx-doc.0.1.1/opam
- packages/satysfi-siunitx/satysfi-siunitx.0.1.1/opam
A comprehensive (SI) units package
-`satysfi-siunitx.0.1.1`
-`satysfi-siunitx-doc.0.1.1`
---
* Homepage: https://github.com/puripuri2100/SATySFi-siunitx
* Source repo: git+https://github.com/puripuri2100/SATySFi-siunitx.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-siunitx/issues
---
> 2 packages from puripuri2100/SATySFi-siunitx at 0.1.1

- packages/satysfi-make-html-doc/satysfi-make-html-doc.0.1.1/opam
- packages/satysfi-make-html/satysfi-make-html.0.1.1/opam
-`satysfi-make-html.0.1.1`: Outputting HTML file using SATySFi's text-mode
-`satysfi-make-html-doc.0.1.1`: Document: Outputting HTML file using SATySFi's text-mode
---
* Homepage: https://github.com/puripuri2100/SATySFi-make-html
* Source repo: git+https://github.com/puripuri2100/SATySFi-make-html.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-make-html/issues
---
> 2 packages from puripuri2100/SATySFiHTML at 0.1.1

- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.1.1/opam
- packages/satysfi-easytable/satysfi-easytable.1.1.1/opam
This PR is created manually because `opam publish` command failed somehow.
---
A SATySFi package to build simple tables
-`satysfi-easytable.1.1.1`
-`satysfi-easytable-doc.1.1.1`
---
* Homepage: https://github.com/monaqa/satysfi-easytable
* Source repo: git+https://github.com/monaqa/satysfi-easytable.git
* Bug tracker: https://github.com/monaqa/satysfi-easytable/issues
---
- ~~~~Add to snapshot `snapshot-stable-0-0-4`~~ (Inconsistent)~~ (Inconsistent)
> 2 packages from monaqa/satysfi-easytable at 1.1.1

- packages/satysfi-easytable/satysfi-easytable.1.1.1/opam
> Add missing dependency on satysfi-base

- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.1/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.1/opam
-`satysfi-figbox.0.1.1`: A SATySFi package for creating charts and placing them in inappropriate positions
-`satysfi-figbox-doc.0.1.1`: Document for satysfi-figbox package
---
* Homepage: https://github.com/monaqa/satysfi-figbox
* Source repo: git+https://github.com/monaqa/satysfi-figbox.git
* Bug tracker: https://github.com/monaqa/satysfi-figbox/issues
---
> 2 packages from monaqa/satysfi-figbox at 0.1.1

- packages/satysfi-md2latex-doc/satysfi-md2latex-doc.0.0.3/opam
- packages/satysfi-md2latex/satysfi-md2latex.0.0.3/opam
-`satysfi-md2latex.0.0.3`: Convert Markdown to LaTeX with SATySFi
-`satysfi-md2latex-doc.0.0.3`: Document of md2latex Package
---
* Homepage: https://github.com/puripuri2100/SATySFi-md2latex
* Source repo: git+https://github.com/puripuri2100/SATySFi-md2latex.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-md2latex/issues
---
> 2 packages from puripuri2100/SATySFi-md2latex at 0.0.3

- packages/satysfi-image-doc/satysfi-image-doc.0.1.0/opam
- packages/satysfi-image/satysfi-image.0.1.0/opam
-`satysfi-image.0.1.0`: Insert image with SATySFi
-`satysfi-image-doc.0.1.0`: Document of an insert image with SATySFi
---
* Homepage: https://github.com/puripuri2100/SATySFi-image
* Source repo: git+https://github.com/puripuri2100/SATySFi-image.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-image/issues
---
> 2 packages from puripuri2100/SATySFi-image at 0.1.0

- packages/satysfi-json-doc/satysfi-json-doc.1.0.1/opam
- packages/satysfi-json/satysfi-json.1.0.1/opam
-`satysfi-json.1.0.1`: JSON parser for SATySFi
-`satysfi-json-doc.1.0.1`: Document of JSON parser for SATySFi
---
* Homepage: https://github.com/puripuri2100/SATySFi-json
* Source repo: git+https://github.com/puripuri2100/SATySFi-json.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-json/issues
---
> 2 packages from puripuri2100/SATySFi-json at 1.0.1

- packages/satysfi-fonts-han-serif-jp-doc/satysfi-fonts-han-serif-jp-doc.1.001R/opam
- packages/satysfi-fonts-han-serif-jp/satysfi-fonts-han-serif-jp.1.001R/opam
-`satysfi-fonts-han-serif-jp.1.001R`: SATySFi Font Package for han serif JP fonts（源ノ明朝）
-`satysfi-fonts-han-serif-jp-doc.1.001R`: Document of SATySFi Font Package for han serif JP fonts
---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-han-serif-jp
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-han-serif-jp.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-han-serif-jp/issues
---
> 2 packages from puripuri2100/SATySFi-fonts-han-serif-jp at 1.001R

- packages/satysfi-fonts-han-sans-jp-doc/satysfi-fonts-han-sans-jp-doc.2.003R/opam
- packages/satysfi-fonts-han-sans-jp/satysfi-fonts-han-sans-jp.2.003R/opam
-`satysfi-fonts-han-sans-jp.2.003R`: SATySFi Font Package for han sans JP fonts（源ノ角ゴシック）
-`satysfi-fonts-han-sans-jp-doc.2.003R`: Document of SATySFi Font Package for han sans JP fonts
---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-han-sans-jp
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-han-sans-jp.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-han-sans-jp/issues
---
> 2 packages from puripuri2100/SATySFi-fonts-han-sans-jp at 2.003R

- .github/workflows/ci.yaml
This PR adds CI against OCaml 4.12.0
> Build against OCaml 4.12.0

- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.2/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.2/opam
-`satysfi-figbox.0.1.2`: A SATySFi package for creating charts and placing them in inappropriate positions
-`satysfi-figbox-doc.0.1.2`: Document for satysfi-figbox package
---
* Homepage: https://github.com/monaqa/satysfi-figbox
* Source repo: git+https://github.com/monaqa/satysfi-figbox.git
* Bug tracker: https://github.com/monaqa/satysfi-figbox/issues
---
> 2 packages from monaqa/satysfi-figbox at 0.1.2

- packages/satysfi-class-jlreq/satysfi-class-jlreq.0.0.2/opam
A document class for SATySFi
---
* Homepage: https://github.com/abenori/satysfi-class-jlreq/
* Source repo: git+https://github.com/abenori/satysfi-class-jlreq.git
* Bug tracker: https://github.com/abenori/satysfi-class-jlreq/issues
---
> Package satysfi-class-jlreq.0.0.2

- README.md
Since we got approvals from the contributors, we can apply CC0-1.0+ license to the repository.
Close https://github.com/na4zagin3/satyrographos-repo/issues/334
> Apply CC0-1.0+ license to the repository

- packages/satysfi-cancel/satysfi-cancel.0.0.1/opam
The cancel package
The SATySFi equivalent of the LateX's cancel package.
---
* Homepage: https://github.com/yuhr/satysfi-cancel
* Source repo: git+https://github.com/yuhr/satysfi-cancel.git
* Bug tracker: https://github.com/yuhr/satysfi-cancel/issues
---
> Package satysfi-cancel.0.0.1

- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.3/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.3/opam
-`satysfi-figbox.0.1.3`: A SATySFi package for creating charts and placing them in inappropriate positions
-`satysfi-figbox-doc.0.1.3`: Document for satysfi-figbox package
---
* Homepage: https://github.com/monaqa/satysfi-figbox
* Source repo: git+https://github.com/monaqa/satysfi-figbox.git
* Bug tracker: https://github.com/monaqa/satysfi-figbox/issues
---
> 2 packages from monaqa/satysfi-figbox at 0.1.3

- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.3.1/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.3.1/opam
- `satysfi-class-slydifi.0.3.1`: A SATySFi document class for creating presentations slides
- `satysfi-class-slydifi-doc.0.3.1`: A SATySFi document class for creating presentations slides
---
> 2 packages from monaqa/slydifi at 0.3.1

- packages/satysfi-railway-doc/satysfi-railway-doc.0.1.0/opam
- packages/satysfi-railway/satysfi-railway.0.1.0/opam
- `satysfi-railway.0.1.0`: Drawing library for SATySFi
- `satysfi-railway-doc.0.1.0`: Drawing library for SATySFi
---
* Homepage: https://github.com/monaqa/satysfi-railway
* Source repo: git+https://github.com/monaqa/satysfi-railway.git
* Bug tracker: https://github.com/monaqa/satysfi-railway/issues
> 2 packages from monaqa/satysfi-railway at 0.1.0

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.8/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.8/opam
-`satysfi-class-yabaitech.0.0.8`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.8`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.8

- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.4.0/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.4.0/opam
A SATySFi document class for creating presentations slides
-`satysfi-class-slydifi.0.4.0`
-`satysfi-class-slydifi-doc.0.4.0`
---
---
> 2 packages from monaqa/slydifi at 0.4.0

- packages/satysfi-pagenumber-doc/satysfi-pagenumber-doc.1.0.0/opam
- packages/satysfi-pagenumber/satysfi-pagenumber.1.0.0/opam
> 2 packages from abenori/satysfi-pagenumber at 1.0.0

- packages/satysfi/satysfi.0.0.3+dev2018.10.29/opam
- packages/satysfi/satysfi.0.0.3+dev2019.02.10/opam
- packages/satysfi/satysfi.0.0.3+dev2019.02.13/opam
- packages/satysfi/satysfi.0.0.3+dev2019.03.10/opam
- packages/satysfi/satysfi.0.0.3+dev2019.07.14/opam
- packages/satysfi/satysfi.0.0.3+dev2019.11.16/opam
- packages/satysfi/satysfi.0.0.3/opam
- packages/satysfi/satysfi.0.0.4+dev2020.02.09/opam
- packages/satysfi/satysfi.0.0.4+dev2020.02.16/opam
- packages/satysfi/satysfi.0.0.4+dev2020.02.22/opam
- packages/satysfi/satysfi.0.0.4+dev2020.04.05/opam
- packages/satysfi/satysfi.0.0.4+dev2020.04.25/opam
- packages/satysfi/satysfi.0.0.4+dev2020.06.07/opam
- packages/satysfi/satysfi.0.0.4/opam
- packages/satysfi/satysfi.0.0.5+dev2020.09.05/opam
- packages/satysfi/satysfi.0.0.5-59-g32f2525/opam
- packages/satysfi/satysfi.0.0.5-83-g360d941/opam
- packages/satysfi/satysfi.0.0.5/opam
- packages/satysfi/satysfi.0.0.6-25-g4083234/opam
- packages/satysfi/satysfi.0.0.6-32-g9dbd61d/opam
- packages/satysfi/satysfi.0.0.6-43-ga86452bc/opam
- packages/satysfi/satysfi.0.0.6-53-g2867e4d9/opam
- packages/satysfi/satysfi.0.0.6/opam
SATySFi declares dependency on depext while it in fact does not.
This PR addresses https://github.com/gfngfn/SATySFi/issues/287
> Remove unneeded dependency on depext

- .github/workflows/ci.yaml
Use opam-repositories for setup-ocaml and cleaned up useless steps
> Use opam-repositories

- packages/satysfi-code-printer-doc/satysfi-code-printer-doc.1.0.0/opam
- packages/satysfi-code-printer/satysfi-code-printer.1.0.0/opam
> 2 packages from puripuri2100/satysfi-code-printer at 1.0.0

- ci.sh
- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.1/opam
- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.3/opam
- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.2.0/opam
- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.3.1/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.2.0/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.3.1/opam
- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.0.0/opam
- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.1.1/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.1/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.2/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.3/opam
Old packages of satysfi-class-slydifi lack upper version constraints.  This PR adds them.
>  Fix version constraints of satysfi-class-slydifi

- packages/satysfi-parallel-doc/satysfi-parallel-doc.0.1.0/opam
- packages/satysfi-parallel/satysfi-parallel.0.1.0/opam
Typesetting two texts in parallel
-`satysfi-parallel.0.1.0`
-`satysfi-parallel-doc.0.1.0`
---
* Homepage: https://github.com/MasWag/satysfi-parallel
* Source repo: git+https://github.com/MasWag/satysfi-parallel.git
* Bug tracker: https://github.com/MasWag/satysfi-parallel/issues
---
> 2 packages from MasWag/satysfi-parallel at 0.1.0

- ci.sh
- packages/satysfi-parallel-doc/satysfi-parallel-doc.0.2.0/opam
- packages/satysfi-parallel/satysfi-parallel.0.2.0/opam
Typesetting two texts in parallel
-`satysfi-parallel.0.2.0`
-`satysfi-parallel-doc.0.2.0`
---
* Homepage: https://github.com/MasWag/satysfi-parallel
* Source repo: git+https://github.com/MasWag/satysfi-parallel.git
* Bug tracker: https://github.com/MasWag/satysfi-parallel/issues
---
> 2 packages from MasWag/satysfi-parallel at 0.2.0

- .github/workflows/ci.yaml
- scripts/take-snapshot
- snapshot-develop--1.opam
- snapshot-stable-0-0-6--1.opam
This PR adds new snapshots with minor versions:
- develop--1
- stable-0-0-6--1
Those snapshot will have package names `satyrographos-snapshot-${DEVELOP_OR_STABLE}-${SATYSFI_VERSION}-1+${DATE}`.
Closes https://github.com/na4zagin3/satyrographos-repo/issues/394
The new snapshots were created without
- azmath
- class-slydifi
- easytable
- figbox
> Add new snapshot minor versions

- .github/workflows/pr-followup.yaml
- .github/workflows/pr.yaml
This addresses the error https://github.com/na4zagin3/satyrographos-repo/actions/runs/1595868860 caused by itemization in https://github.com/na4zagin3/satyrographos-repo/pull/400
- test test
- test
> Properly ignore non-follow-up part in body

- ci.sh
Currently old-deps steps are skipped because of the flipped condition.
> Fix flipped skip conditions

- .github/workflows/ci.yaml
We need to disable build against OCaml 4.12 until https://github.com/ocaml/opam-repository/pull/20284 is merged
> Temporarily disable OCaml 4.12

- .github/workflows/ci.yaml
- ci.sh
> Skip oldest-deps check when opam-0install fails

- snapshot-develop--1.opam
- snapshot-stable-0-0-6--1.opam
Other libraries in the snapshots depend on easytable.
Ideally, easytable should be removed from the snapshots until its test library (i.e., doc library for Satyrographos 0.0.2) is restored, but we cannot do that.
> Add back easytable.1.1.1 to the snapshots

- .github/workflows/ci.yaml
Every SATySFi library in a snapshot should _not_ depend on any library that is not in the snapshot.
> Check if the snapshot is consistent

- packages/satysfi-colorbox-doc/satysfi-colorbox-doc.0.1.0/opam
- packages/satysfi-colorbox/satysfi-colorbox.0.1.0/opam
-`satysfi-colorbox.0.1.0`: A SATySFi package for Colored boxes
-`satysfi-colorbox-doc.0.1.0`: Document of Colorbox
---
* Homepage: https://github.com/abenori/satysfi-colorbox
* Source repo: git+https://github.com/abenori/satysfi-colorbox.git
* Bug tracker: https://github.com/abenori/satysfi-colorbox/issues
---
> 2 packages from abenori/satysfi-colorbox at 0.1.0

- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.5.0/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.5.0/opam
A SATySFi document class for creating presentations slides
-`satysfi-class-slydifi.0.5.0`
-`satysfi-class-slydifi-doc.0.5.0`
---
---
- ~~Add to snapshot `snapshot-develop--1`~~ (inconsistent-snapshot +satysfi-figbox)
- ~~Add to snapshot …
> 2 packages from monaqa/slydifi at 0.5.0

- packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam
satysfi-fonts-inconsolata's lower version of Satyrographos is wrong.  This commit fixes it.
> Fix wrong lower version of satysfi-fonts-inconsolata

- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.9/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.9/opam
-`satysfi-class-yabaitech.0.0.9`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.9`: Document: The yabaitech.tokyo SATySFi class file
---
---
> 2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.9

- packages/satysfi-colorbox-doc/satysfi-colorbox-doc.0.1.1/opam
- packages/satysfi-colorbox/satysfi-colorbox.0.1.1/opam
-`satysfi-colorbox.0.1.1`: A SATySFi package for Colored boxes
-`satysfi-colorbox-doc.0.1.1`: Document of Colorbox
---
* Homepage: https://github.com/abenori/satysfi-colorbox
* Source repo: git+https://github.com/abenori/satysfi-colorbox.git
* Bug tracker: https://github.com/abenori/satysfi-colorbox/issues
---
:camel: Pull-request generated by opam-publish v2.1.0
> 2 packages from abenori/satysfi-colorbox at 0.1.1

- packages/satysfi-xpath-doc/satysfi-xpath-doc.0.2.0/opam
- packages/satysfi-xpath/satysfi-xpath.0.2.0/opam
-`satysfi-xpath.0.2.0`: Advanced path algorithms in SATySFi
-`satysfi-xpath-doc.0.2.0`: Docs of advanced path algorithms in SATySFi
---
* Homepage: https://github.com/yasuo-ozu/satysfi-xpath
* Source repo: git+https://github.com/yasuo-ozu/satysfi-xpath.git
* Bug tracker: https://github.com/yasuo-ozu/satysfi-xpath/issues
---
:camel: Pull-request generated by opam-publish v2.1.0
> 2 packages from yasuo-ozu/satysfi-xpath at 0.2.0

- packages/satysfi-dist/satysfi-dist.0.0.7/opam
- packages/satysfi/satysfi.0.0.7/opam
- snapshot-stable-0-0-7.opam
SATySFi 0.0.7 was released with https://github.com/gfngfn/SATySFi/pull/324
This PR adds it to the repo.
> Add SATySFi 0.0.7

- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.4/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.4/opam
- `satysfi-figbox.0.1.4`: A SATySFi package for creating charts and placing them in inappropriate positions
- `satysfi-figbox-doc.0.1.4`: Document for satysfi-figbox package
---
* Homepage: https://github.com/monaqa/satysfi-figbox
* Source repo: git+https://github.com/monaqa/satysfi-figbox.git
* Bug tracker: https://github.com/monaqa/satysfi-figbox/issues
> 2 packages from monaqa/satysfi-figbox at 0.1.4

- packages/satysfi-num-conversion/satysfi-num-conversion.0.1.1/opam
This should fix a build error found at https://github.com/na4zagin3/satyrographos-repo/pull/434:
```
+ opam exec -- satyrographos install
Reading runtime dist: /home/na4zagin3/Documents/Development/satysfi/satyrographos-repo/_opam/share/satysfi/dist
Read user libraries: ()
Reading opam libraries: (assert-eq assert-eq-doc bibyfi bibyfi-doc cancel class-exdesign
class-exdesign-doc class-stjarticle class-stjarticle-doc debug-show-value
debug-show-value-doc dist fonts-asana-math fonts-asana-math-doc
fonts-computer-modern-unicode fonts-dejavu fonts-dejavu-doc fonts-noto-emoji
fonts-noto-sans fonts-noto-sans-cjk-jp fonts-noto-sans-cjk-sc
fonts-noto-sans-cjk-sc-doc fonts-noto-serif fonts-noto-serif-cjk-jp
fonts-theano fonts-theano-doc grcnum grcnum-doc karnaugh karnaugh-doc lipsum
lipsum-doc …
```
> fix wrong dependency declaration of satysfi-num-conversion.0.1.1

- ci.sh
This is to catch a problem where files Satyrigraphos creates are recognized as _contents-changed_ instead of _added_.
> Check OPAM package integrity

- packages/satysfi-latexcmds-doc/satysfi-latexcmds-doc.0.1.0/opam
> Fix wrong satyrographos package name specified at satysfi-latexcmds-doc.0.1.0

- ci.sh
This commit workarounds https://github.com/ocaml/opam/issues/5132 by restoring `$(opam var prefix)/.opam-switch/install/` after running `opam install --dry-run`.
> Workaround OPAM bug gh-5132

- ci.sh
> make opam_install_dry_run return the actual status code

- packages/satysfi-azmath/satysfi-azmath.0.0.3/opam
satysfi-azmath.3.0.0 actually requires satysfi-base 1.4.0 or later.
> Specify version lowerbound of satysfi-base

- .github/workflows/ci.yaml
- ci.sh
- packages/satysfi-azmath/satysfi-azmath.0.0.1/opam
- packages/satysfi-class-jlreq/satysfi-class-jlreq.0.0.2/opam
- packages/satysfi-class-mdbook-satysfi-doc/satysfi-class-mdbook-satysfi-doc.0.2.0/opam
- packages/satysfi-class-mdbook-satysfi-doc/satysfi-class-mdbook-satysfi-doc.0.3.0/opam
- packages/satysfi-class-mdbook-satysfi/satysfi-class-mdbook-satysfi.0.2.0/opam
- packages/satysfi-class-mdbook-satysfi/satysfi-class-mdbook-satysfi.0.3.0/opam
- packages/satysfi-easytable/satysfi-easytable.1.0.0/opam
- packages/satysfi-easytable/satysfi-easytable.1.1.1/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.1/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.2/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.3/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.4/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.1/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.2/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.3/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.4/opam
- packages/satysfi-json-doc/satysfi-json-doc.1.0.1/opam
- packages/satysfi-json/satysfi-json.1.0.1/opam
This PR adds revdep check and fix wrong dependency declarations on satysfi-base.
> Add revdep check

- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.1.2/opam
- packages/satysfi-easytable/satysfi-easytable.1.1.2/opam
A SATySFi package to build simple tables
- `satysfi-easytable.1.1.2`
- `satysfi-easytable-doc.1.1.2`
---
* Homepage: https://github.com/monaqa/satysfi-easytable
* Source repo: git+https://github.com/monaqa/satysfi-easytable.git
* Bug tracker: https://github.com/monaqa/satysfi-easytable/issues
> 2 packages from monaqa/satysfi-easytable at 1.1.2

- packages/satysfi-cancel/satysfi-cancel.0.0.1/opam
- packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2/opam
> Fix wrong dependencies of satysfi-cancel.0.0.1 and satysfi-class-stjarticle.1.3.2

- .github/workflows/ci.yaml
Reverts na4zagin3/satyrographos-repo#405
OCaml 4.12 itself does not cause the current issue.
> Revert "Temporarily disable OCaml 4.12"

- packages/satysfi-algorithm-doc/satysfi-algorithm-doc.1.0.0/opam
- packages/satysfi-algorithm/satysfi-algorithm.1.0.0/opam
- `satysfi-algorithm.1.0.0` : Typesetting pseudo-code in SATySFi
- `satysfi-algorithm-doc.1.0.0` : Document for satysfi-algorithm
---
Homepage: https://github.com/pickoba/satysfi-algorithm
Source repo: git+https://github.com/pickoba/satysfi-algorithm.git
Bug tracker: https://github.com/pickoba/satysfi-algorithm/issues
> 2 packages from pickoba/satysfi-algorithm at 1.0.0

- .github/workflows/ci-comment.yaml
The artifacts for CI Comment lacks pull-number.txt and other mandatory files sometimes.
https://github.com/na4zagin3/satyrographos-repo/runs/6544416224?check_suite_focus=true
```
Archive:  pr-248617550.zip
inflating: pr-248617550/comment.txt  
Archive:  pr-248617551.zip
inflating: pr-248617551/comment.txt  
Archive:  pr-248617552.zip
inflating: pr-248617552/comment.txt  
Archive:  pr-248617553.zip
inflating: pr-248617553/comment.txt  
``` …
> Ignore comment files when pull-number is empty

- packages/satysfi-matrixcd-doc/satysfi-matrixcd-doc.0.1.0/opam
- packages/satysfi-matrixcd/satysfi-matrixcd.0.1.0/opam
This is a pull request for package updates.  As I meat an error with opam publish, I do it manually.
-satysfi-matrixcd.0.1.0
-satysfi-matrixcd-doc.0.1.0
> 2 packages from abenori/satysfi-matrixcd at 0.1.0

- packages/satysfi-json-doc/satysfi-json-doc.1.1.3/opam
- packages/satysfi-json/satysfi-json.1.1.3/opam
JSON parser for SATySFi
- `satysfi-json.1.1.3`
- `satysfi-json-doc.1.1.3`
---
- Homepage: https://github.com/puripuri2100/SATySFi-json
- Source repo: git+https://github.com/puripuri2100/SATySFi-json.git
- Bug tracker: https://github.com/puripuri2100/SATySFi-json/issues
> 2 packages from puripuri2100/satysfi-json at 1.1.3

- packages/satysfi-chemfml/satysfi-chemfml.1.0.1/opam
satysfi-chemfml supports SATySFi 0.0.7
> Update dependency of satysfi-chemfml

- packages/satysfi-csvtable-doc/satysfi-csvtable-doc.1.0.0/opam
- packages/satysfi-csvtable/satysfi-csvtable.1.0.0/opam
A SATySFi package to embed CSV into tables.
- `satysfi-csvtable.1.0.0`
- `satysfi-csvtable-doc.1.0.0`
---
- Homepage: https://github.com/qwjyh/satysfi-csvtable
- Source repo: git+https://github.com/qwjyh/satysfi-csvtable.git
- Bug tracker: https://github.com/qwjyh/satysfi-csvtable/issues
> 2 packages from qwjyh/satysfi-csvtable at 1.0.0

- packages/satysfi-fonts-ibm-plex-sans-jp-doc/satysfi-fonts-ibm-plex-sans-jp-doc.1.0.0/opam
- packages/satysfi-fonts-ibm-plex-sans-jp/satysfi-fonts-ibm-plex-sans-jp.1.0.0/opam
-`satysfi-fonts-ibm-plex-sans-jp.1.0.0`: SATySFi Font Package for IBM Plex typeface
-`satysfi-fonts-ibm-plex-sans-jp-doc.1.0.0`: Docs for SATySFi Font Package for IBM Plex typeface
---
* Homepage: https://github.com/monaqa/satysfi-fonts-ibm-plex-sans-jp
* Source repo: git+https://github.com/monaqa/satysfi-fonts-ibm-plex-sans-jp.git
* Bug tracker: https://github.com/monaqa/satysfi-fonts-ibm-plex-sans-jp/issues
> 2 packages from monaqa/satysfi-fonts-ibm-plex-sans-jp at 1.0.0

- packages/satysfi-fonts-material-icons-doc/satysfi-fonts-material-icons-doc.1.0.1/opam
- packages/satysfi-fonts-material-icons/satysfi-fonts-material-icons.1.0.1/opam
-`satysfi-fonts-material-icons.1.0.1`: SATySFi Font Package for Google Material Icons
-`satysfi-fonts-material-icons-doc.1.0.1`: Docs for SATySFi Font Package for Google Material Icons
---
* Homepage: https://github.com/monaqa/satysfi-fonts-material-icons
* Source repo: git+https://github.com/monaqa/satysfi-fonts-material-icons.git
* Bug tracker: https://github.com/monaqa/satysfi-fonts-material-icons/issues
> 2 packages from monaqa/satysfi-fonts-material-icons at 1.0.1

- packages/satysfi-csvtable-doc/satysfi-csvtable-doc.1.1.0/opam
- packages/satysfi-csvtable/satysfi-csvtable.1.1.0/opam
A SATySFi package to embed CSV into tables.
- satysfi-csvtable.1.1.0
- satysfi-csvtable-doc.1.1.0
------
- Homepage: https://github.com/qwjyh/satysfi-csvtable
- Source repo: git+https://github.com/qwjyh/satysfi-csvtable.git
- Bug tracker: https://github.com/qwjyh/satysfi-csvtable/issues
> 2 packages from qwjyh/satysfi-csvtable at 1.1.0

- ci.sh
SATySFi and Satyrographos were mistakenly excluded from oldest-dep test.
> Include SATySFi and Satyrographos in the oldest dep test

- .github/workflows/ci-comment.yaml
- .github/workflows/ci.yaml
- .github/workflows/pr-followup.yaml
- .github/workflows/pr.yaml
- .github/workflows/update-develop.yaml
This PR specifies `submodules: true` input for `actions/checkout@v2` action.
> Fetch submodule during CI

- packages/satysfi-algorithm-doc/satysfi-algorithm-doc.1.0.0/opam
- packages/satysfi-algorithm/satysfi-algorithm.1.0.0/opam
- packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
- packages/satysfi-arrows/satysfi-arrows.0.1.0/opam
- packages/satysfi-assert-eq-doc/satysfi-assert-eq-doc.0.1.2/opam
- packages/satysfi-assert-eq/satysfi-assert-eq.0.1.2/opam
- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.3/opam
- packages/satysfi-azmath/satysfi-azmath.0.0.3/opam
- packages/satysfi-base/satysfi-base.1.5.0/opam
- packages/satysfi-json-doc/satysfi-json-doc.1.1.3/opam
- packages/satysfi-json/satysfi-json.1.1.3/opam
This PR split from #504.  This updates version restriction on satysfi for packages that start with `a`.
- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (Inconsistent)
> Update upper version restriction for satysfi: A

- packages/satysfi-bibyfi-doc/satysfi-bibyfi-doc.0.0.2/opam
- packages/satysfi-bibyfi/satysfi-bibyfi.0.0.2/opam
- packages/satysfi-cancel/satysfi-cancel.0.0.1/opam
- packages/satysfi-chemfml-doc/satysfi-chemfml-doc.1.0.1/opam
- packages/satysfi-chemfml/satysfi-chemfml.1.0.1/opam
- packages/satysfi-class-cv-doc/satysfi-class-cv-doc.0.1.0/opam
- packages/satysfi-class-cv/satysfi-class-cv.0.1.0/opam
- packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.3.1/opam
- packages/satysfi-class-exdesign/satysfi-class-exdesign.0.3.1/opam
- packages/satysfi-class-jlreq/satysfi-class-jlreq.0.0.3/opam
- packages/satysfi-class-mdbook-satysfi-doc/satysfi-class-mdbook-satysfi-doc.0.3.0/opam
- packages/satysfi-class-mdbook-satysfi/satysfi-class-mdbook-satysfi.0.3.0/opam
- packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.5.0/opam
- packages/satysfi-class-slydifi/satysfi-class-slydifi.0.5.0/opam
- packages/satysfi-class-stjarticle-doc/satysfi-class-stjarticle-doc.1.3.2/opam
- packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2/opam
- packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.9/opam
- packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.9/opam
- packages/satysfi-code-printer-doc/satysfi-code-printer-doc.1.1.1/opam
- packages/satysfi-code-printer/satysfi-code-printer.1.1.1/opam
- packages/satysfi-csv-doc/satysfi-csv-doc.1.0.0/opam
- packages/satysfi-csv/satysfi-csv.1.0.0/opam
- packages/satysfi-csvtable-doc/satysfi-csvtable-doc.1.1.0/opam
- packages/satysfi-csvtable/satysfi-csvtable.1.1.0/opam
This PR split from https://github.com/na4zagin3/satyrographos-repo/pull/504. This updates version restriction on satysfi for packages that start with `b` and `c`.
- ~~Add to snapshot `snapshot-develop`~~ (inconsistent-snapshot +satysfi-figbox)
- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (inconsistent-snapshot +satysfi-figbox)
> Update upper version restriction for satysfi: B and C

- packages/satysfi-ncsq-doc/satysfi-ncsq-doc.2.1.0/opam
- packages/satysfi-ncsq/satysfi-ncsq.2.1.0/opam
- packages/satysfi-num-conversion-doc/satysfi-num-conversion-doc.0.1.4/opam
- packages/satysfi-num-conversion/satysfi-num-conversion.0.1.4/opam
- packages/satysfi-pagenumber-doc/satysfi-pagenumber-doc.1.0.0/opam
- packages/satysfi-pagenumber/satysfi-pagenumber.1.0.0/opam
- packages/satysfi-pagestyle-doc/satysfi-pagestyle-doc.1.0.0/opam
- packages/satysfi-pagestyle/satysfi-pagestyle.1.0.0/opam
- packages/satysfi-parallel-doc/satysfi-parallel-doc.0.2.0/opam
- packages/satysfi-parallel/satysfi-parallel.0.2.0/opam
- packages/satysfi-quotation-doc/satysfi-quotation-doc.0.2.0/opam
- packages/satysfi-quotation/satysfi-quotation.0.2.0/opam
- packages/satysfi-railway-doc/satysfi-railway-doc.0.1.0/opam
- packages/satysfi-railway/satysfi-railway.0.1.0/opam
- packages/satysfi-ruby-doc/satysfi-ruby-doc.0.1.2/opam
- packages/satysfi-ruby/satysfi-ruby.0.1.2/opam
This PR split from https://github.com/na4zagin3/satyrographos-repo/pull/504. This updates version restriction on satysfi for packages that start with `n` to `r`.
> Update upper version restriction for satysfi: N, P, Q, and R

- packages/satysfi-grcnum-doc/satysfi-grcnum-doc.0.2/opam
- packages/satysfi-grcnum/satysfi-grcnum.0.2/opam
- packages/satysfi-image-doc/satysfi-image-doc.0.1.0/opam
- packages/satysfi-image/satysfi-image.0.1.0/opam
- packages/satysfi-karnaugh-doc/satysfi-karnaugh-doc.0.0.1/opam
- packages/satysfi-karnaugh/satysfi-karnaugh.0.0.1/opam
- packages/satysfi-lipsum-doc/satysfi-lipsum-doc.0.2.1/opam
- packages/satysfi-lipsum/satysfi-lipsum.0.2.1/opam
- packages/satysfi-make-html-doc/satysfi-make-html-doc.0.1.1/opam
- packages/satysfi-make-html/satysfi-make-html.0.1.1/opam
- packages/satysfi-make-latex-doc/satysfi-make-latex-doc.0.2.0/opam
- packages/satysfi-make-latex/satysfi-make-latex.0.2.0/opam
- packages/satysfi-make-markdown/satysfi-make-markdown.0.1.0/opam
- packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/opam
- packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/opam
- packages/satysfi-matrixcd-doc/satysfi-matrixcd-doc.0.1.0/opam
- packages/satysfi-matrixcd/satysfi-matrixcd.0.1.0/opam
- packages/satysfi-md2latex-doc/satysfi-md2latex-doc.0.0.3/opam
- packages/satysfi-md2latex/satysfi-md2latex.0.0.3/opam
- packages/satysfi-musikui-doc/satysfi-musikui-doc.0.1.1/opam
- packages/satysfi-musikui/satysfi-musikui.0.1.1/opam
This PR split from https://github.com/na4zagin3/satyrographos-repo/pull/504. This updates version restriction on satysfi for packages that start with `g` to `m`.
> Update upper version restriction for satysfi: G, I, K, L, and M

- packages/satysfi-simple-itemize-doc/satysfi-simple-itemize-doc.1.0.2/opam
- packages/satysfi-simple-itemize/satysfi-simple-itemize.1.0.2/opam
- packages/satysfi-siunitx-doc/satysfi-siunitx-doc.0.1.1/opam
- packages/satysfi-siunitx/satysfi-siunitx.0.1.1/opam
- packages/satysfi-test/satysfi-test.0.0.1/opam
- packages/satysfi-texlogo-doc/satysfi-texlogo-doc.0.1.1/opam
- packages/satysfi-texlogo/satysfi-texlogo.0.1.1/opam
- packages/satysfi-tombo-doc/satysfi-tombo-doc.0.2.0/opam
- packages/satysfi-tombo/satysfi-tombo.0.2.0/opam
- packages/satysfi-uline-doc/satysfi-uline-doc.0.2.2/opam
- packages/satysfi-uline/satysfi-uline.0.2.2/opam
- packages/satysfi-zrbase/satysfi-zrbase.0.4.0/opam
This PR split from https://github.com/na4zagin3/satyrographos-repo/pull/504. This updates version restriction on satysfi for packages that start with `s` to `z`.
> Update upper version restriction for satysfi: S to Z

- packages/satysfi-debug-show-value-doc/satysfi-debug-show-value-doc.0.1.2/opam
- packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.2/opam
- packages/satysfi-derive/satysfi-derive.1.0.0/opam
- packages/satysfi-easytable-doc/satysfi-easytable-doc.1.1.2/opam
- packages/satysfi-easytable/satysfi-easytable.1.1.2/opam
- packages/satysfi-enumitem-doc/satysfi-enumitem-doc.3.0.1/opam
- packages/satysfi-enumitem/satysfi-enumitem.3.0.1/opam
- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.4/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.4/opam
- packages/satysfi-fss-doc/satysfi-fss-doc.0.2.0/opam
- packages/satysfi-fss-fontset-bodoni-star/satysfi-fss-fontset-bodoni-star.2.3/opam
- packages/satysfi-fss/satysfi-fss.0.2.0/opam
This PR split from https://github.com/na4zagin3/satyrographos-repo/pull/504. This updates version restriction on satysfi for packages that start with `d` to `f`.
> Update upper version restriction for satysfi: D, E, and F

- packages/satysfi-latexcmds-doc/satysfi-latexcmds-doc.0.1.2/opam
- packages/satysfi-latexcmds/satysfi-latexcmds.0.1.2/opam
> 2 packages from yasuo-ozu/satysfi-latexcmds at 0.1.2

- packages/satysfi-class-cv-doc/satysfi-class-cv-doc.0.1.1/opam
- packages/satysfi-class-cv/satysfi-class-cv.0.1.1/opam
-satysfi-class-cv.0.1.1: SATySFi class file for Curriculum Vitae
-satysfi-class-cv-doc.0.1.1: Documentation of a class for CV
Homepage: https://github.com/MasWag/cv-satysfi
Source repo: git+https://github.com/MasWag/cv-satysfi.git
Bug tracker: https://github.com/MasWag/cv-satysfi/issues
> 7 packages from MasWag/satyrographos-repo at satysfi-class-cv-0.1.1

- .github/workflows/ci.yaml
- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.3+1/files/azmath-enumitem-3.patch
- packages/satysfi-azmath-doc/satysfi-azmath-doc.0.0.3+1/opam
- snapshot-develop.opam
- snapshot-stable-0-0-6--1.opam
- snapshot-stable-0-0-7.opam
- snapshot-stable-0-0-8.opam
This allows to add other packages depending on azmath to snapshots.
> Add satysfi-azmath-doc.0.0.3+1 that supports enumitem 3

- packages/satysfi-figbox-doc/satysfi-figbox-doc.0.1.4/opam
- packages/satysfi-figbox/satysfi-figbox.0.1.4/opam
Specify upper bound of `satysfi-base`.
> Update version constraint on satysfi-dist

- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.02.13/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.03.10/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.07.14/opam
- packages/satysfi-dist/satysfi-dist.0.0.3+dev2019.11.16/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.09/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.16/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.22/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.05/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.25/opam
- packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.06.07/opam
- packages/satysfi-dist/satysfi-dist.0.0.4/opam
- packages/satysfi-dist/satysfi-dist.0.0.5+dev2020.09.05/opam
- packages/satysfi-dist/satysfi-dist.0.0.5-59-g32f2525/opam
- packages/satysfi-dist/satysfi-dist.0.0.5-83-g360d941/opam
- packages/satysfi-dist/satysfi-dist.0.0.5/opam
- packages/satysfi-dist/satysfi-dist.0.0.6-25-g4083234/opam
- packages/satysfi-dist/satysfi-dist.0.0.6-32-g9dbd61d/opam
- packages/satysfi-dist/satysfi-dist.0.0.6-43-ga86452bc/opam
- packages/satysfi-dist/satysfi-dist.0.0.6-53-g2867e4d9/opam
- packages/satysfi-dist/satysfi-dist.0.0.6/opam
- packages/satysfi-dist/satysfi-dist.0.0.7-20-g748112c2/opam
- packages/satysfi-dist/satysfi-dist.0.0.7-26-g9f4b68ec/opam
- packages/satysfi-dist/satysfi-dist.0.0.7/opam
- packages/satysfi-dist/satysfi-dist.0.0.8/opam
- packages/satysfi/satysfi.0.0.3+dev2018.10.29/opam
- packages/satysfi/satysfi.0.0.3/opam
- resources/satysfi-dist.template
Replaced all occurrences of `http://www.gust.org.pl` to `https://www.gust.org.pl` as `www.gust.org.pl` returns 404 for HTTP access.
* Fix #575 
* Related to gfngfn/satysfi#411
Tested with `satysfi-dist.0.0.5`, `satysfi-dist.0.0.6`, `satysfi-dist.0.0.7` and `satysfi-dist.0.0.8` (installation of less than 0.0.5 was difficult because it requires OCaml 3, but I think it is old enough)
- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (No …
> [satysfi-dist] Use HTTPS for GUST fonts

- ci.sh
This commit disables option `--strict` because new variable `with-dev-setup`  has already been used by some packages in opam-repository.
Fixes https://github.com/na4zagin3/satyrographos-repo/issues/655
> Disable --strict option for OPAM 2.0/2.1

- .github/workflows/pr.yaml
Added `assigned` and `synchronize` triggers to `pull_request_target`.
> Trigger PR CI for more conditions

- .github/workflows/ci.yaml
We need results from failed jobs.
https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f
> Upload result file regardless of task failure

- packages/satysfi-footnote-scheme-ext/satysfi-footnote-scheme-ext.0.0.1/opam
A package extending footnote-scheme.satyh that allows floating boxes at the bottom of pages.
- satysfi-footnote-scheme-ext.0.0.1
---
Homepage: https://github.com/sano-jin/satysfi-footnote-scheme-ext
Source repo: git+https://github.com/sano-jin/satysfi-footnote-scheme-ext.git
Bug tracker: https://github.com/sano-jin/satysfi-footnote-scheme-ext/issues
- Add to snapshot `snapshot-stable-0-0-10`
- Add to snapshot `snapshot-stable-0-0-11`
- Add to …
> Package satysfi-footnote-scheme-ext.0.0.1

- packages/satysfi-class-cv-doc/satysfi-class-cv-doc.0.2.0/opam
- packages/satysfi-class-cv/satysfi-class-cv.0.2.0/opam
> Package cv-satysfi 0.2.0

- .github/workflows/ci-comment.yaml
- .github/workflows/ci.yaml
- .github/workflows/update-develop.yaml
- Add to snapshot `snapshot-stable-0-0-10`
- Add to snapshot `snapshot-stable-0-0-11`
- Add to snapshot `snapshot-stable-0-0-8`
> Update ocaml-install action to v3
