packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.03.10/files/fix-install-libs.patch
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.03.10/opam
packages/satysfi/satysfi.0.0.3+dev2019.03.10/opam

Add satysfi.0.0.3+dev2019.03.10 https://github.com/gfngfn/SATySFi/commit/6137f5ce23f4d0f0203dd5531655f06720ba2583

Add satysfi.0.0.3+dev2019.03.10

---

.travis.yml
packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2+satysfi0.0.3+satyrograhos0.0.1/files/fix-makefile-glob.patch
packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2+satysfi0.0.3+satyrograhos0.0.1/opam

Name: stjarticle
Package name: satysfi-class-stjarticle
Site: https://github.com/puripuri2100/stjarticle
Installation method: Satyrographos-0.0.1 Makefile

Add satysfi-class-stjarticle

---

.travis.yml
packages/satysfi-fonts-theano-doc/satysfi-fonts-theano-doc.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.2/opam

-`satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.2`: SATySFi Font Package for Alexey Kryukov's Theano
Classical Fonts
-`satysfi-fonts-theano-doc.2.0+satysfi0.0.3+satyrograhos0.0.2`: Document of SATySFi Font Package for Alexey Kryukov's
Theano Classical Fonts
---
* Homepage: https://github.com/na4zagin3/SATySFi-fonts-theano
* Source repo: git+https://github.com/na4zagin3/SATySFi-fonts-theano.git
* Bug tracker: https://github.com/na4zagin3/SATySFi-fonts-theano/issues
---

2 packages from na4zagin3/SATySFi-fonts-theano at 2.0+satysfi0.0.3+satyrograhos0.0.2

---

packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.02.10/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.02.13/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.03.10/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.07.14/opam
packages/satysfi/satysfi.0.0.3/opam

Cf. https://github.com/gfngfn/SATySFi/pull/203 & https://github.com/na4zagin3/satyrographos-repo/pull/27

Update URL of IPAexfont

---

.travis.yml
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/files/example.patch
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/files/readme-ja.patch
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/files/readme.patch
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/files/satyristes.patch
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/opam
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/files/example.patch
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/files/readme-ja.patch
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/files/readme.patch
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/files/satyristes.patch
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/opam

This PR adds the following packages:
- satysfi-matrix.0.0.1+dev2019.10.15
- satysfi-matrix-doc.0.0.1+dev2019.10.15
that corresponding to https://github.com/nekketsuuu/satysfi-matrix/commit/366d80b7f3e58d89686bc8b381e5a373e0699b5f
Closes #14

Add satysfi-matrix.0.0.1+dev2019.10.15

---

.travis.yml
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/files/article-ja.patch
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/files/manual.patch
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/files/readme.patch
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/files/satyristes.patch
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/opam
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/files/article-ja.patch
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/files/manual.patch
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/files/readme.patch
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/files/satyristes.patch
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/opam

Add satysfi-class-exdesign.0.2

---

.travis.yml
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.02.10/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.02.13/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.03.10/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.07.14/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3+dev2019.11.16/opam
packages/satysfi-lib-dist/satysfi-lib-dist.0.0.3/opam
packages/satysfi-lib-doc/satysfi-lib-doc.0.0.0+dev2019.11.10/opam
packages/satysfi-lib/satysfi-lib.0.0.0+dev2019.11.10/opam

Add satysfi-base to CI and show renaming announces.

Show rename announces

---

.travis.yml
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/opam
packages/satysfi-class-stjarticle-doc/satysfi-class-stjarticle-doc.1.3.2/opam
packages/satysfi-dist/satysfi-dist.0.0.4/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.4/opam
packages/satysfi/satysfi.0.0.4/opam

Add satysfi 0.0.4

---

.travis.yml
packages/satysfi-base/satysfi-base.1.1.1/opam
packages/satysfi-class-exdesign-doc/satysfi-class-exdesign-doc.0.2/opam
packages/satysfi-class-exdesign/satysfi-class-exdesign.0.2/opam
packages/satysfi-class-stjarticle-doc/satysfi-class-stjarticle-doc.1.3.2/opam
packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2/opam
packages/satysfi-fonts-dejavu-doc/satysfi-fonts-dejavu-doc.2.37/opam
packages/satysfi-fonts-dejavu/satysfi-fonts-dejavu.2.37/opam
packages/satysfi-fonts-theano-doc/satysfi-fonts-theano-doc.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
packages/satysfi-grcnum-doc/satysfi-grcnum-doc.0.2/opam
packages/satysfi-grcnum/satysfi-grcnum.0.2/opam
packages/satysfi-matrix-doc/satysfi-matrix-doc.0.0.1+dev2019.10.15/opam
packages/satysfi-matrix/satysfi-matrix.0.0.1+dev2019.10.15/opam
packages/satysfi-zrbase/satysfi-zrbase.0.2.1+satysfi0.0.3+satyrographos0.0.2/opam

Bulk update on version constraints.
https://satysfi.slack.com/archives/CSKJZMV33/p1579961358022600
Closes #49

Bump version constraints to support SATySFi 0.0.4

---

.travis.yml
packages/satysfi-class-slydifi/satysfi-class-slydifi.0.1.0/opam

A SATySFi document class for creating presentations slides
A SATySFi document class for creating presentations slides.
---
---
---
Closes #17

Package satysfi-class-slydifi.0.1.0

---

.travis.yml
packages/satysfi-enumitem/satysfi-enumitem.1.0.1/opam

A SATySFi package for creating itemized lists
A SATySFi package for creating itemized lists.
---
* Homepage: https://github.com/monaqa/satysfi-enumitem
* Source repo: git+https://github.com/monaqa/satysfi-enumitem.git
* Bug tracker: https://github.com/monaqa/satysfi-enumitem/issues
---

Package satysfi-enumitem.1.0.1

---

.travis.yml
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.09/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.09/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.09/opam

Add satysfi.0.0.4+dev2020.02.09

---

.gitignore
README.md
resources/fix-install-libs.patch
resources/satysfi-dist.template
scripts/add-satysfi

This PR adds a script to add satysfi and satysfi-dist packages.

Add script/add-satysfi

---

.travis.yml
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.22/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.02.22/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.22/opam

This version includes a fix for NotoSans-ExtraCondensedThinItalic.
https://satysfi.slack.com/archives/CBBFCSZ34/p1582291669066600

Add satysfi.0.0.4+dev2020.02.22

---

packages/satysfi-enumitem/satysfi-enumitem.1.1.0/opam

A SATySFi package for creating itemized lists
A SATySFi package for creating itemized lists.
---
* Homepage: https://github.com/monaqa/satysfi-enumitem
* Source repo: git+https://github.com/monaqa/satysfi-enumitem.git
* Bug tracker: https://github.com/monaqa/satysfi-enumitem/issues
---

Package satysfi-enumitem.1.1.0

---

.travis.yml
packages/satysfi-make-html/satysfi-make-html.0.1.0/opam
packages/satysfi-make-markdown/satysfi-make-markdown.0.1.0/opam
packages/satysfi-siunitx/satysfi-siunitx.0.1+satysfi0.0.3+satyrograhos0.0.1/opam
packages/satysfi-siunitx/satysfi-siunitx.0.1/opam

add:
- [satysfi-make-html](https://github.com/puripuri2100/SATySFi-make-html)
- [satysfi-make-markdown](https://github.com/puripuri2100/SATySFi-make-markdown)
fix:
- [satysfi-siunitx](https://github.com/puripuri2100/SATySFi-siunitx)

Add two packages and fix one package

---

.travis.yml
packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.0/opam

Add [`satysfi-debug-show-value.0.1.0`](https://github.com/puripuri2100/SATySFi-debug-show-value).
"Stringify SATySFi's value"

Add satysfi-debug-show-value

---

.travis.yml
packages/satysfi-assert-eq/satysfi-assert-eq.0.1.0/opam

Add [`satysfi-assert-eq.0.1.0`](https://github.com/puripuri2100/SATySFi-assert-eq).
"Provides function as the Rust's assert_eq! macro"

Add satysfi-assert-eq

---

.travis.yml
packages/satysfi-num-conversion/satysfi-num-conversion.0.1.1/opam

Add [`satysfi-num-conversion.0.1.1`](https://github.com/puripuri2100/SATySFi-num-conversion)
"Convert numbers to the following notation"

Add satysfi-num-conversion

---

.travis.yml
packages/satysfi-musikui/satysfi-musikui.0.1.0/opam

This package is for easy expression of arithmetical restorations with SATySFi
This package is for easy expression of arithmetical restorations with SATySFi
---
* Homepage: https://github.com/puripuri2100/musikui.satyh
* Source repo: git+https://github.com/puripuri2100/musikui.satyh.git
* Bug tracker: https://github.com/puripuri2100/musikui.satyh/issues
---

Package satysfi-musikui.0.1.0

---

packages/satyrographos/satyrographos.0.0.1.1/opam
packages/satysfi-assert-eq/satysfi-assert-eq.0.1.0/opam
packages/satysfi-assert-eq/satysfi-assert-eq.0.1.1/opam
packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.0/opam
packages/satysfi-debug-show-value/satysfi-debug-show-value.0.1.1/opam
packages/satysfi-fonts-noto-emoji-doc/satysfi-fonts-noto-emoji-doc.1.05+uh/opam
packages/satysfi-fonts-noto-emoji/satysfi-fonts-noto-emoji.1.05+uh/opam
packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.1+r2/opam
packages/satysfi-simple-itemize/satysfi-simple-itemize.1.0.0/opam
packages/satysfi-siunitx/satysfi-siunitx.0.1/opam
packages/satysfi-zrbase/satysfi-zrbase.0.2.1+satysfi0.0.3+satyrographos0.0.1/opam
packages/satysfi-zrbase/satysfi-zrbase.0.2.1+satysfi0.0.3+satyrographos0.0.2/opam

This PR adds checksums to opam files that lacks them.
Additionally, `name` and `synopsis` fields from zrbase opam files.

Add checksums

---

.travis.yml
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.25/files/fix-hash.patch
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.25/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.04.25/opam
packages/satysfi/satysfi.0.0.4+dev2020.04.25/opam
resources/satysfi-dist.template
satyrographos-repo-test-develop.opam

This PR adds satysfi.0.0.4+dev2020.04.25. Also updates the template of satysfi-dist.
Closes #109

Add satysfi.0.0.4+dev2020.04.25

---

packages/satysfi-bibyfi/satysfi-bibyfi.0.0.1/opam
satyrographos-repo-test-develop.opam
satyrographos-repo-test-stable.opam

A bibliography framework for SATySFi
This project has been under developing. The API may be broken dramatically and suddenly
A bibliography framework for SATySFi
This project is inspired by cs-thesis and borrowing many codes from it.
---
* Homepage: https://github.com/namachan10777/BiByFi
* Source repo: git+https://github.com/namachan10777/BiByFi.git
* Bug tracker: https://github.com/namachan10777/BiByFi/issues
---

Package satysfi-bibyfi.0.0.1

---

packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.06.07/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.4+dev2020.06.07/opam
packages/satysfi/satysfi.0.0.4+dev2020.06.07/opam
satyrographos-repo-test-develop.opam

This version started to depend on a YoJson fork named yojson-with-position

 Add satysfi.0.0.4+dev2020.06.07

---

packages/satysfi-enumitem-doc/satysfi-enumitem-doc.2.0.0/opam
packages/satysfi-enumitem/satysfi-enumitem.2.0.0/opam

A SATySFi package for creating itemized lists
-`satysfi-enumitem.2.0.0`
-`satysfi-enumitem-doc.2.0.0`
---
* Homepage: https://github.com/monaqa/satysfi-enumitem
* Source repo: git+https://github.com/monaqa/satysfi-enumitem.git
* Bug tracker: https://github.com/monaqa/satysfi-enumitem/issues
---

2 packages from monaqa/satysfi-enumitem at 2.0.0

---

packages/satysfi-dist/satysfi-dist.0.0.5/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.5/opam
packages/satysfi/satysfi.0.0.5/opam

Change log: https://github.com/gfngfn/SATySFi/blob/master/CHANGELOG.md#005---2020-07-11

Add satysfi.0.0.5

---

packages/satysfi-base/satysfi-base.1.3.0/opam
satyrographos-repo-test-develop.opam
satyrographos-repo-test-stable-0-0-4.opam
satyrographos-repo-test-stable-0-0-5.opam

This PR follows https://github.com/na4zagin3/satyrographos-repo/pull/125 up.

Fix version constraint of satysfi-base

---

snapshot-develop.opam
snapshot-stable-0-0-5.opam

This PR follows up https://github.com/na4zagin3/satyrographos-repo/pull/131

Add satysfi-ncsq to the snapshots

---

packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.4+2020.07.20/opam
packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.5+2020.07.20/opam
scripts/take-snapshot

This PR adds a script to copy snapshot files into `packages/` and snapshots 2020.07.20.

Add snapshots 2020.07.20

---

.github/workflows/pr.yaml

In order to allow commenting, this PR adds github-token environment variable.

Add github-token

---

.github/workflows/pr-comment.yaml

This PR tries to add a comment bot which is triggered by a comment prefixed with `#snapshot/update`.
A comment like this will run script/update-snapshot
```
#snapshot/update
develop
stable 0.0.4
stable 0.0.5
```

Add pr-comment.yaml action

---

.travis.yml
travis.sh

This PR have Travis CI install and uninstall each an added or modified package.

Run CI with added/modified packages

---

travis.sh

This PR has CI skip a package whose build failures with a result containing «No available version of satysfi satisfies the constraints».

Skip packages if their dependencies are not coherent

---

.travis.yml

This PR have Travis use Ubuntu Bionic instead of Xenial.

Use Ubuntu Bionic

---

snapshot-develop.opam

Follows up https://github.com/na4zagin3/satyrographos-repo/pull/154

Add satysfi-class-yabaitech.0.0.2 to develop snapshot

---

packages/satyrographos-snapshot-develop/satyrographos-snapshot-develop.0.0.5+2020.08.24/opam
packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.4+2020.07.20/opam
packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.4+2020.08.24/opam
packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.5+2020.07.20/opam
packages/satyrographos-snapshot-stable/satyrographos-snapshot-stable.0.0.5+2020.08.24/opam
snapshot-develop.opam
snapshot-stable-0-0-4.opam
snapshot-stable-0-0-5.opam
travis.sh

[Automated] Take snapshots

---

travis.sh

With this PR, OCaml-version mismatched snapshots are skipped during individual-package testing.
Also the script will fetch origin/master to calculate diff

Skip OCaml-version mismatched snapshots

---

travis.sh

After this change, `master` branch will be overwritten by `origin/master`.

Specify branch target branch name of git fetch

---

scripts/add-satysfi

This fixes a bug where add-satysfi never gets newer versions.

Fix order of git pull and git checkout

---

travis.sh

Fixes https://github.com/na4zagin3/satyrographos-repo/issues/235

Increase OPAMSOLVERTIMEOUT to 300

---

.github/workflows/ci.yaml
ci.sh

This is the initial step of migration for GitHub Actions (https://github.com/na4zagin3/satyrographos-repo/issues/240).
Based on https://github.com/gfngfn/SATySFi/pull/250/files

Add GitHub Action ci.yaml

---

snapshot-develop.opam
snapshot-stable-0-0-5.opam

Add satysfi-derive.1.0.0 to the snapshots

---

packages/satysfi-dist/satysfi-dist.0.0.5-83-g360d941/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.5-83-g360d941/opam
packages/satysfi/satysfi.0.0.5-83-g360d941/opam
snapshot-develop.opam

Add SATySFi develop 0.0.5-83-g360d941

---

snapshot-develop.opam
snapshot-stable-0-0-5.opam

Follow up #265

---

packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam

#265 で追加したopamファイルに書いていたリンクが間違っていたので修正しました。
また、2度も誤ったプルリクを送ってしまい、申し訳ありません。

fix link #265

---

snapshot-develop.opam
snapshot-stable-0-0-5.opam

Follow up #266

---

.github/workflows/ci.yaml
packages/satysfi-dist/satysfi-dist.0.0.6/files/fix-install-libs.patch
packages/satysfi-dist/satysfi-dist.0.0.6/opam
packages/satysfi/satysfi.0.0.6/opam
snapshot-stable-0-0-6.opam

Add SATySFi 0.0.6

---

packages/satysfi-assert-eq-doc/satysfi-assert-eq-doc.0.1.2/opam

Fix dependency of satysfi-assert-eq-doc

---

packages/satysfi-test/satysfi-test.0.0.1/opam

Fix urls in satysfi-test.0.0.1

---

packages/satysfi-dist/satysfi-dist.0.0.6-25-g4083234/opam
packages/satysfi/satysfi.0.0.6-25-g4083234/opam
resources/satysfi-dist.template
scripts/add-satysfi
snapshot-develop.opam

Add satysfi.0.0.6-25-g4083234

---

packages/satysfi/satysfi.0.0.3+dev2019.02.10/opam
packages/satysfi/satysfi.0.0.3+dev2019.02.13/opam
packages/satysfi/satysfi.0.0.3+dev2019.03.10/opam
packages/satysfi/satysfi.0.0.3+dev2019.07.14/opam
packages/satysfi/satysfi.0.0.3+dev2019.11.16/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.09/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.16/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.22/opam
packages/satysfi/satysfi.0.0.4+dev2020.04.05/opam
packages/satysfi/satysfi.0.0.4+dev2020.04.25/opam
packages/satysfi/satysfi.0.0.4+dev2020.06.07/opam
packages/satysfi/satysfi.0.0.4/opam
packages/satysfi/satysfi.0.0.5+dev2020.09.05/opam
packages/satysfi/satysfi.0.0.5-59-g32f2525/opam
packages/satysfi/satysfi.0.0.5-83-g360d941/opam
packages/satysfi/satysfi.0.0.5/opam
packages/satysfi/satysfi.0.0.6-25-g4083234/opam
packages/satysfi/satysfi.0.0.6/opam

See https://github.com/gfngfn/SATySFi/pull/264 for more details

Limit omd version

---

snapshot-stable-0-0-5.opam
snapshot-stable-0-0-6.opam

Bump Satyrographos version to 0.0.2.10

---

packages/satysfi-dist/satysfi-dist.0.0.6-32-g9dbd61d/opam
packages/satysfi/satysfi.0.0.6-32-g9dbd61d/opam
snapshot-develop.opam

Add SATySFi develop satysfi.0.0.6-32-g9dbd61d 

---

snapshot-develop.opam

Update Satyrographos 0.0.2.10 for develop snapshot

---

packages/satysfi-dist/satysfi-dist.0.0.6-43-ga86452bc/opam
packages/satysfi/satysfi.0.0.6-43-ga86452bc/opam
snapshot-develop.opam

Add SATySFi develop satysfi.0.0.6-43-ga86452bc

---

.github/workflows/ci.yaml
ci.sh

Caching `~/.opam` is not recommended by smorimoto: https://twitter.com/_smorimoto/status/1363637158246973442

Use ocaml/setup-ocaml@v2 instead of v1

---

packages/satysfi-dist/satysfi-dist.0.0.6-53-g2867e4d9/opam
packages/satysfi/satysfi.0.0.6-53-g2867e4d9/opam
snapshot-develop.opam

Diff: https://github.com/gfngfn/SATySFi/compare/a86452bc...2867e4d9

Add satysfi.0.0.6-53-g2867e4d9

---

packages/satysfi-latexcmds-doc/satysfi-latexcmds-doc.0.1.0/opam
packages/satysfi-latexcmds-doc/satysfi-latexcmds.0.1.0/opam
packages/satysfi-latexcmds/satysfi-latexcmds.0.1.0/opam

Repo: https://github.com/yasuo-ozu/satysfi-latexcmds

Add satysfi-latexcmds v0.1.0

---

packages/satysfi-pagestyle-doc/satysfi-pagestyle-doc.1.0.0/opam
packages/satysfi-pagestyle/satysfi-pagestyle.1.0.0/opam

2 packages from abenori/satysfi-pagestyle at 1.0.0

---

packages/satysfi-enumitem-doc/satysfi-enumitem-doc.3.0.1/opam
packages/satysfi-enumitem/satysfi-enumitem.3.0.1/opam

A SATySFi package for creating itemized lists
-`satysfi-enumitem.3.0.1`
-`satysfi-enumitem-doc.3.0.1`
---
* Homepage: https://github.com/monaqa/satysfi-enumitem
* Source repo: git+https://github.com/monaqa/satysfi-enumitem.git
* Bug tracker: https://github.com/monaqa/satysfi-enumitem/issues
---

2 packages from monaqa/satysfi-enumitem at 3.0.1

---

.github/workflows/ci.yaml

This workarounds https://github.com/na4zagin3/satyrographos/issues/287

Workaround satyrographos bug 287

---

snapshot-develop.opam
snapshot-stable-0-0-5.opam
snapshot-stable-0-0-6.opam

Use Satyrographos 0.0.2.11

---

ci.sh

Fix undefined variable expansion SKIP_OLDEST_DEPS

---

.github/workflows/ci.yaml

Reverts na4zagin3/satyrographos-repo#397

Revert "Workaround satyrographos bug 287"

---

.github/workflows/ci.yaml

Disable order check

---

.github/workflows/ci-comment.yaml
.github/workflows/ci.yaml

Fix consistent checking logic

---

packages/satysfi-class-cv-doc/satysfi-class-cv-doc.0.1.0/opam
packages/satysfi-class-cv/satysfi-class-cv.0.1.0/opam

-`satysfi-class-cv.0.1.0`: SATySFi class file for Curriculum Vitae
-`satysfi-class-cv-doc.0.1.0`: Documentation of a class for CV
---
* Homepage: https://github.com/MasWag/cv-satysfi
* Source repo: git+https://github.com/MasWag/cv-satysfi.git
* Bug tracker: https://github.com/MasWag/cv-satysfi/issues
---

Packages satysfi-class-cv.0.1.0 and satysfi-class-cv-doc.0.1.0

---

snapshot-stable-0-0-6--1.opam
snapshot-stable-0-0-7.opam

bump parallel in snaphost 0.0.6-1 and 0.0.7

---

packages/satysfi-fonts-asana-math/satysfi-fonts-asana-math.000.958+1+satysfi0.0.4/opam

Add CTAN mirror sites for asana-math

Add mirrors of asana-math

---

ci.sh

This commit workaround OPAM Bug https://github.com/ocaml/opam/issues/5132 by
ignoring files that should have been uninstalled.

Workaround OPAM Bug 5132

---

ci.sh

Enable OPAMPRECISETRACKING

---

ci.sh

Test oldest-deps against only SATySFi ecosystem

---

snapshot-develop--1.opam
snapshot-develop.opam
snapshot-stable-0-0-4.opam
snapshot-stable-0-0-5.opam
snapshot-stable-0-0-6--1.opam
snapshot-stable-0-0-6.opam
snapshot-stable-0-0-7.opam

Fix license of current snapshots

---

.github/workflows/ci-comment.yaml
.github/workflows/ci.yaml
ci.sh

Support output for comment

---

packages/satysfi-fonts-asana-math/satysfi-fonts-asana-math.000.958+1+satysfi0.0.4/opam
packages/satysfi-fonts-bodoni-star-doc/satysfi-fonts-bodoni-star-doc.2.3+satysfi0.0.5/opam
packages/satysfi-fonts-bodoni-star/satysfi-fonts-bodoni-star.2.3+satysfi0.0.5/opam
packages/satysfi-fonts-computer-modern-unicode/satysfi-fonts-computer-modern-unicode.0.7.0+satysfi0.0.4/opam
packages/satysfi-fonts-cormorant-doc/satysfi-fonts-cormorant-doc.3.601+satysfi0.0.5/opam
packages/satysfi-fonts-cormorant/satysfi-fonts-cormorant.3.601+satysfi0.0.5/opam
packages/satysfi-fonts-junicode-doc/satysfi-fonts-junicode-doc.1.0002+satysfi0.0.5/opam
packages/satysfi-fonts-junicode/satysfi-fonts-junicode.1.0002+satysfi0.0.5/opam
packages/satysfi-fonts-noto-emoji/satysfi-fonts-noto-emoji.1.05+uh+2/opam
packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.1.004+satysfi0.0.4/opam
packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.2.001+1+satysfi0.0.4/opam
packages/satysfi-fonts-noto-sans-cjk-sc/satysfi-fonts-noto-sans-cjk-sc.2.001+1/opam
packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.000+satysfi0.0.4/opam
packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.001+1+satysfi0.0.4/opam
packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.1.001+satysfi0.0.4/opam
packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.2.001+1+satysfi0.0.4/opam
packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.000+satysfi0.0.4/opam
packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.001+1+satysfi0.0.4/opam
packages/satysfi-fonts-theano-doc/satysfi-fonts-theano-doc.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.1+r2/opam
packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.2/opam

- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (Inconsistent)

Fix license of font packages

---

packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.0.1/opam
packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.1.0/opam
packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.2.0/opam
packages/satysfi-ncsq-doc/satysfi-ncsq-doc.1.0.0/opam
packages/satysfi-ncsq-doc/satysfi-ncsq-doc.2.0.0/opam
packages/satysfi-ncsq/satysfi-ncsq.0.0.1/opam
packages/satysfi-ncsq/satysfi-ncsq.0.1.0/opam
packages/satysfi-ncsq/satysfi-ncsq.0.2.0/opam
packages/satysfi-ncsq/satysfi-ncsq.1.0.0/opam
packages/satysfi-ncsq/satysfi-ncsq.2.0.0/opam
packages/satysfi-ncsq/satysfi-ncsq.2.1.0/opam

- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (Inconsistent)

Fix dependency declaration of ncsq

---

ci.sh

Close https://github.com/na4zagin3/satyrographos-repo/issues/390

Comment should be posted from ci.sh

---

scripts/add-satysfi

Support adding alpha versions of SATySFi

---

.github/workflows/ci-comment.yaml
.github/workflows/ci.yaml

Distinguish ci results from different ocaml versions

---

packages/satysfi-xpath-doc/satysfi-xpath-doc.0.3.0/opam
packages/satysfi-xpath-gr/satysfi-xpath-gr.0.3.0/opam
packages/satysfi-xpath/satysfi-xpath.0.3.0/opam

3 packages from yasuo-ozu/satysfi-xpath at 0.3.0

---

packages/satysfi-latexcmds-doc/satysfi-latexcmds-doc.0.1.1/opam
packages/satysfi-latexcmds/satysfi-latexcmds.0.1.1/opam

2 packages from yasuo-ozu/satysfi-latexcmds at 0.1.1

---

.github/workflows/update-develop.yaml
scripts/update-snapshot-satysfi

This PR automates update of the develop snapshot

Automate update dev snapshot

---

scripts/update-snapshot-satysfi

Avoid from updating snapshot with an empty SATySFi version

---

packages/satysfi-base/satysfi-base.1.5.0/opam

- ~~Add to snapshot `snapshot-stable-0-0-7`~~ (Inconsistent)

Package satysfi-base.1.5.0

---

.github/workflows/ci.yaml
packages/satysfi-class-jlreq/satysfi-class-jlreq.0.0.3/opam
packages/satysfi-matrixcd-doc/satysfi-matrixcd-doc.0.1.0/opam
packages/satysfi-matrixcd/satysfi-matrixcd.0.1.0/opam
snapshot-develop--1.opam
snapshot-stable-0-0-6--2.opam
snapshot-stable-0-0-7--1.opam

Add new snapshots with satysfi-base.1.5.0

---

snapshot-develop.opam
snapshot-stable-0-0-6--1.opam
snapshot-stable-0-0-7.opam
snapshot-stable-0-0-8.opam

Add slidify to the snapshots

---

packages/satysfi-actuarial-doc/satysfi-actuarial-doc.0.0.1/opam
packages/satysfi-actuarial/satysfi-actuarial.0.0.1/opam

A package for actuarial notations.

2 packages from arakur/satysfi-actuarial at 0.0.1

---

packages/satysfi-xml-doc/satysfi-xml-doc.1.0.3/opam
packages/satysfi-xml/satysfi-xml.1.0.3/opam

`satysfi-xml.1.0.3` and `satysfi-xml-doc.1.0.0`
ML parser with SATySFi.
- Homepage: https://github.com/puripuri2100/SATySFi-xml
- Source repo: git+https://github.com/puripuri2100/SATySFi-xml.git
- Bug tracker: https://github.com/puripuri2100/SATySFi-xml/issues

add satysfi-xml.1.0.3

---

.github/workflows/ci.yaml

Build SATySFi 0.0.4 against OCaml 4.07.1

---

.github/workflows/automatic-rebase.yaml

https://github.com/cirrus-actions/rebase
The command is limited to org member or repo collaborator.

Add automatic rebase command

---

.github/workflows/pr-comment-welcome.yaml
.github/workflows/pr.yaml

Post a welcome comment only when opened

---

.github/workflows/ci.yaml
snapshot-stable-0-0-10.opam

- Add `stable-snapshot-stable-0-0-10.opam`
- update CI file

Add stable-snapshot-stable-0-0-10.opam

---

packages/satysfi/satysfi.0.0.10/opam
packages/satysfi/satysfi.0.0.3+dev2018.10.29/opam
packages/satysfi/satysfi.0.0.3+dev2019.02.10/opam
packages/satysfi/satysfi.0.0.3+dev2019.02.13/opam
packages/satysfi/satysfi.0.0.3+dev2019.03.10/opam
packages/satysfi/satysfi.0.0.3+dev2019.07.14/opam
packages/satysfi/satysfi.0.0.3+dev2019.11.16/opam
packages/satysfi/satysfi.0.0.3/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.09/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.16/opam
packages/satysfi/satysfi.0.0.4+dev2020.02.22/opam
packages/satysfi/satysfi.0.0.4+dev2020.04.05/opam
packages/satysfi/satysfi.0.0.4+dev2020.04.25/opam
packages/satysfi/satysfi.0.0.4+dev2020.06.07/opam
packages/satysfi/satysfi.0.0.4/opam
packages/satysfi/satysfi.0.0.5+dev2020.09.05/opam
packages/satysfi/satysfi.0.0.5-59-g32f2525/opam
packages/satysfi/satysfi.0.0.5-83-g360d941/opam
packages/satysfi/satysfi.0.0.5/opam
packages/satysfi/satysfi.0.0.6-25-g4083234/opam
packages/satysfi/satysfi.0.0.6-32-g9dbd61d/opam
packages/satysfi/satysfi.0.0.6-43-ga86452bc/opam
packages/satysfi/satysfi.0.0.6-53-g2867e4d9/opam
packages/satysfi/satysfi.0.0.6/opam
packages/satysfi/satysfi.0.0.7-20-g748112c2/opam
packages/satysfi/satysfi.0.0.7-26-g9f4b68ec/opam
packages/satysfi/satysfi.0.0.7/opam
packages/satysfi/satysfi.0.0.8/opam
packages/satysfi/satysfi.0.0.9-6-ge0304803/opam

Backports https://github.com/gfngfn/SATySFi/pull/426/files
- ~~Add to snapshot `snapshot-stable-0-0-10`~~ (No updates)

Update version constraints

---

.github/workflows/ci.yaml
snapshot-stable-0-0-11.opam

- ~~Add to snapshot `snapshot-stable-0-0-10`~~ (No updates)

Add snapshot-stable-0-0-11

---

.github/workflows/ci-comment.yaml

- Add to snapshot `snapshot-stable-0-0-10`
- Add to snapshot `snapshot-stable-0-0-11`
- Add to snapshot `snapshot-stable-0-0-8`

Address breaking change of actions/github-script v5
